# Generated by Django 4.2.14 on 2026-01-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permachat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='titre',
        ),
        migrations.AddField(
            model_name='room',
            name='estPermanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
