# Generated by Django 4.2.27 on 2026-05-25 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permachat', '0002_rename_name_room_titre_room_estpermanent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_creation',)},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_added',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='room',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
