# Generated by Django 4.2.27 on 2026-05-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permachat', '0003_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='created_on',
            new_name='date_creation',
        ),
    ]
