# Generated by Django 4.2.27 on 2026-05-26 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permachat', '0004_rename_created_on_room_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='titre',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_]*?(-[a-zA-Z0-9_]+)*$')]),
        ),
    ]
