# Generated by Django 4.2.27 on 2026-05-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permachat', '0005_alter_room_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
