# Generated by Django 2.2.28 on 2023-10-23 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0017_auto_20231021_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='article lié'),
        ),
    ]
