# Generated by Django 2.2.28 on 2023-12-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0019_auto_20231024_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance_participantreunion',
            name='type_trajet',
            field=models.CharField(choices=[('0', 'Véhicule personnel'), ('1', 'Covoiturage'), ('2', 'Distanciel')], default='0', max_length=30, verbose_name='Type de trajet'),
        ),
    ]
