# Generated by Django 2.2.28 on 2023-12-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0021_auto_20231219_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance_participantreunion',
            name='distance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Distance aller (en km)'),
        ),
    ]
