# Generated by Django 4.2.14 on 2024-09-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0023_auto_20240412_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance_participantreunion',
            name='distance',
            field=models.FloatField(blank=True, help_text="Mettre juste le nombre de kilomètres (sans ajouter 'km')", null=True, verbose_name='Distance aller (en km)'),
        ),
    ]
