# Generated by Django 4.2.14 on 2025-07-08 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bourseLibre', '0134_alter_salon_type_salon'),
        ('defraiement', '0024_alter_distance_participantreunion_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteDeFrais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(verbose_name='Date de la cotisation')),
                ('date_note', models.DateField(verbose_name='Date du paiement')),
                ('titre', models.CharField(max_length=10, verbose_name='Titre de la note de frais')),
                ('categorie', models.IntegerField(choices=[(0, 'Achat'), (1, 'Hebergement'), (2, 'Restauration'), (3, 'Autre')], default='0', verbose_name='Categorie de frais')),
                ('montant', models.CharField(max_length=10, verbose_name='Montant de la note de frais')),
                ('moyen', models.IntegerField(choices=[(0, 'Virement'), (1, 'Chèque'), (2, 'Espèce'), (3, 'Autre')], verbose_name='Moyen de paiement')),
                ('detail', models.TextField(null=True)),
                ('estArchive', models.BooleanField(default=False, verbose_name='Archiver la Note de frais')),
                ('asso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.asso')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='defraiement.participantreunion')),
            ],
        ),
    ]
