# Generated by Django 4.2.14 on 2025-07-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0025_notedefrais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedefrais',
            name='date_creation',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
    ]
