# Generated by Django 4.2.14 on 2025-08-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0026_alter_notedefrais_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedefrais',
            name='titre',
            field=models.CharField(max_length=120, verbose_name='Titre de la note de frais'),
        ),
    ]
