# Generated by Django 4.2.27 on 2026-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0027_alter_notedefrais_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='categorie',
            field=models.CharField(choices=[('0', 'Réunion équipe'), ('1', 'Troc de Graine'), ('2', 'Atelier'), ('3', 'Rencontre'), ('4', 'FestiGraines'), ('5', 'Visite de Jardin'), ('6', 'Autre'), ('7', 'Cercle Ancrage'), ('8', 'Cercle Labo'), ('9', 'Cercle Education'), ('10', 'Cercle Jardins'), ('11', 'Cercle Evenement'), ('12', 'Réunion CS'), ('13', 'Evenement'), ('14', 'Manifestation')], default='0', max_length=30, verbose_name='Dossier'),
        ),
    ]
