# Generated by Django 4.2.27 on 2026-09-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0028_alter_reunion_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance_participantreunion',
            name='km_manuel',
            field=models.BooleanField(default=False, verbose_name='Les km ont été spécifiés manuellement'),
        ),
    ]
