# Generated by Django 4.2.27 on 2026-09-30 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0160_alter_articleliens_type_lien'),
        ('defraiement', '0029_distance_participantreunion_km_manuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.projet'),
        ),
        migrations.AlterField(
            model_name='distance_participantreunion',
            name='distance',
            field=models.FloatField(blank=True, help_text="Mettre juste le nombre de kilomètres Aller (sans ajouter 'km', le nombre sera doublé pour le calcul du total))", null=True, verbose_name='Distance aller (en km)'),
        ),
    ]
