# Generated by Django 4.2.27 on 2026-09-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0160_alter_articleliens_type_lien'),
        ('defraiement', '0030_reunion_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.projet'),
        ),
    ]
