# Generated by Django 4.2.27 on 2026-10-06 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0141_profil_adherent_irri66_profil_adherent_jppb_and_more'),
        ('defraiement', '0031_alter_reunion_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantreunion',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.adresse'),
        ),
    ]
