# Generated by Django 2.2.28 on 2023-01-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBRang_inpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RG_LEVEL', models.CharField(max_length=4)),
                ('RANG', models.CharField(max_length=5)),
                ('DETAIL', models.CharField(max_length=30)),
                ('DETAIL_EN', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DBStatut_inpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDRE', models.CharField(max_length=4)),
                ('STATUT', models.CharField(max_length=2)),
                ('DESCRIPTION', models.CharField(max_length=30)),
                ('DEFINITION', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REGNE', models.CharField(max_length=15)),
                ('PHYLUM', models.CharField(max_length=30)),
                ('CLASSE', models.CharField(max_length=50)),
                ('ORDRE', models.CharField(max_length=50)),
                ('FAMILLE', models.CharField(max_length=50)),
                ('SOUS_FAMILLE', models.CharField(max_length=50)),
                ('TRIBU', models.CharField(max_length=50)),
                ('GROUP1_INPN', models.CharField(max_length=10)),
                ('GROUP2_INPN', models.CharField(max_length=10)),
                ('GROUP3_INPN', models.CharField(max_length=10)),
                ('CD_NOM', models.CharField(max_length=10)),
                ('CD_TAXSUP', models.CharField(max_length=10)),
                ('CD_SUP', models.CharField(max_length=10)),
                ('CD_REF', models.CharField(max_length=10)),
                ('RANG', models.CharField(max_length=5)),
                ('LB_NOM', models.CharField(max_length=100)),
                ('NOM_COMPLET', models.CharField(max_length=150)),
                ('NOM_COMPLET_HTML', models.CharField(max_length=200)),
                ('NOM_VALIDE', models.CharField(max_length=150)),
                ('NOM_VERN', models.CharField(max_length=150)),
                ('NOM_VERN_ENG', models.CharField(max_length=150)),
                ('HABITAT', models.CharField(max_length=5)),
                ('FR', models.CharField(max_length=2)),
                ('GF', models.CharField(max_length=2)),
                ('MAR', models.CharField(max_length=2)),
                ('GUA', models.CharField(max_length=2)),
                ('SM', models.CharField(max_length=2)),
                ('SB', models.CharField(max_length=2)),
                ('SPM', models.CharField(max_length=2)),
                ('MAY', models.CharField(max_length=2)),
                ('EPA', models.CharField(max_length=2)),
                ('REU', models.CharField(max_length=2)),
                ('SA', models.CharField(max_length=2)),
                ('TA', models.CharField(max_length=2)),
                ('TAAF', models.CharField(max_length=2)),
                ('PF', models.CharField(max_length=2)),
                ('NC', models.CharField(max_length=2)),
                ('WF', models.CharField(max_length=2)),
                ('CLI', models.CharField(max_length=2)),
                ('URL', models.CharField(max_length=200)),
                ('infos_supp', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
