# Generated by Django 2.2.28 on 2023-01-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBHabitat_inpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HABITAT', models.CharField(max_length=4)),
                ('LB_HABITAT', models.CharField(max_length=2)),
                ('DEFINITION', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='DBVern_inpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CD_VERN', models.CharField(max_length=4)),
                ('CD_NOM', models.CharField(max_length=2)),
                ('LB_VERN', models.TextField(blank=True, null=True)),
                ('NOM_VERN_SOURCE', models.CharField(max_length=400)),
                ('LANGUE', models.CharField(max_length=400)),
                ('ISO639_3', models.CharField(max_length=400)),
                ('PAYS', models.CharField(max_length=400)),
            ],
        ),
    ]
