# Generated by Django 2.2.28 on 2023-01-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0002_dbhabitat_inpn_dbvern_inpn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbrang_inpn',
            name='RG_LEVEL',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dbvern_inpn',
            name='CD_NOM',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dbvern_inpn',
            name='CD_VERN',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plante',
            name='CD_NOM',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plante',
            name='CD_REF',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plante',
            name='CD_SUP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plante',
            name='CD_TAXSUP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plante',
            name='RANG',
            field=models.IntegerField(),
        ),
    ]
