# Generated by Django 2.2.28 on 2023-01-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0003_auto_20230125_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='plante',
            name='LB_AUTEUR',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
