# Generated by Django 2.2.28 on 2023-01-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0007_auto_20230125_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='CD_REF',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plante',
            name='CD_SUP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plante',
            name='GROUP1_INPN',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plante',
            name='GROUP2_INPN',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plante',
            name='GROUP3_INPN',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plante',
            name='HABITAT',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='plante',
            name='LB_AUTEUR',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plante',
            name='LB_NOM',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='plante',
            name='NOM_COMPLET',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plante',
            name='NOM_COMPLET_HTML',
            field=models.CharField(max_length=250),
        ),
    ]
