# Generated by Django 2.2.28 on 2023-01-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0008_auto_20230125_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbvern_inpn',
            name='CD_VERN',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='plante',
            name='CD_NOM',
            field=models.IntegerField(unique=True),
        ),
    ]
