# Generated by Django 2.2.28 on 2023-01-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0009_auto_20230125_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbhabitat_inpn',
            name='HABITAT',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plante',
            name='HABITAT',
            field=models.IntegerField(),
        ),
    ]
