# Generated by Django 2.2.28 on 2023-01-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0010_auto_20230125_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plante',
            name='id',
        ),
        migrations.AlterField(
            model_name='plante',
            name='CD_NOM',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
