# Generated by Django 2.2.28 on 2023-01-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0012_auto_20230126_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbstatut_inpn',
            name='DEFINITION',
            field=models.TextField(null=True),
        ),
    ]
