# Generated by Django 2.2.28 on 2023-01-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0013_auto_20230126_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbhabitat_inpn',
            name='DEFINITION',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dbhabitat_inpn',
            name='LB_HABITAT',
            field=models.CharField(max_length=3),
        ),
    ]
