# Generated by Django 2.2.28 on 2023-01-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0015_auto_20230126_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='NOM_COMPLET',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plante',
            name='NOM_COMPLET_HTML',
            field=models.TextField(null=True),
        ),
    ]
