# Generated by Django 2.2.28 on 2023-01-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0017_auto_20230126_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_importeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
                ('lg_debut', models.IntegerField(default=0)),
                ('lg_fin', models.IntegerField(default=0)),
            ],
        ),
    ]
