# Generated by Django 2.2.28 on 2023-01-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0018_db_importeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='HABITAT',
            field=models.CharField(max_length=40),
        ),
    ]
