# Generated by Django 2.2.28 on 2023-01-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0019_auto_20230126_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='CD_SUP',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='plante',
            name='CD_TAXSUP',
            field=models.CharField(max_length=6),
        ),
    ]
