# Generated by Django 2.2.28 on 2023-01-27 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0020_auto_20230126_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jardin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardins.Plante')),
            ],
        ),
    ]
