# Generated by Django 2.2.28 on 2023-01-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0021_jardin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='LB_AUTEUR',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plante',
            name='LB_NOM',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plante',
            name='NOM_VALIDE',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='plante',
            name='NOM_VERN',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='plante',
            name='NOM_VERN_ENG',
            field=models.CharField(max_length=250),
        ),
    ]
