# Generated by Django 2.2.28 on 2023-01-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0022_auto_20230127_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_importeur',
            name='texte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
