# Generated by Django 2.2.28 on 2023-01-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0023_db_importeur_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='CD_SUP',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='plante',
            name='CD_TAXSUP',
            field=models.CharField(max_length=8),
        ),
    ]
