# Generated by Django 2.2.28 on 2023-06-21 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bourseLibre', '0098_auto_20230225_0207'),
        ('jardins', '0025_auto_20230621_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jardins',
            new_name='Jardin',
        ),
    ]
