# Generated by Django 2.2.28 on 2023-06-21 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jardins', '0026_auto_20230621_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits au site seulement'), ('2', 'Invisible')], default='', max_length=30, verbose_name='Visibilité de la grainotheque sur le site'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='categorie',
            field=models.CharField(choices=[('0', 'Collectif (associatif, ouvrier, familial, communal, ...) '), ('1', 'Privé')], default='', max_length=30, verbose_name='Type de jardin'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='email_contact',
            field=models.EmailField(max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Numéro de telephone de contact'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='titre',
            field=models.CharField(max_length=250, verbose_name='Nom du jardin'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='visibilite',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits au site seulement'), ('2', 'Invisible')], default='', max_length=30, verbose_name='Visibilité du jardin sur le site'),
        ),
        migrations.CreateModel(
            name='InscriptionJardin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('jardin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jardin_suivi', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jardin_suiveur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionGrainotheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('grainotek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grainotheque_suivi', to='jardins.Grainotheque')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grainotheque_suiveur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
