# Generated by Django 2.2.28 on 2023-06-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0028_auto_20230621_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='jardin',
            name='fonctionnement',
            field=models.TextField(help_text='Un bref descriptif du fonctionnement du jardin', null=True),
        ),
        migrations.AddField(
            model_name='jardin',
            name='horaires',
            field=models.TextField(help_text="Horaires d'ouverture (s'il y a lieu)", null=True),
        ),
        migrations.AddField(
            model_name='jardin',
            name='permapotes_id',
            field=models.CharField(max_length=250, null=True, verbose_name='Identifiants sur permapotes.com'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='description',
            field=models.TextField(help_text='Un bref descriptif du jardin', null=True),
        ),
    ]
