# Generated by Django 2.2.28 on 2023-07-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0029_auto_20230621_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grainotheque',
            name='visibilite',
        ),
        migrations.RemoveField(
            model_name='jardin',
            name='visibilite',
        ),
        migrations.AddField(
            model_name='grainotheque',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits (visible seulement aux inscrits)'), ('2', 'Invisible')], default='', max_length=30, verbose_name="Visibilité du jardin sur l'annuaire'"),
        ),
        migrations.AddField(
            model_name='grainotheque',
            name='visibilite_carte',
            field=models.CharField(choices=[('0', 'Adresse, nom et référent visibles publiquement'), ('1', 'Inscrits (visible seulement aux inscrits)'), ('2', 'Adresse invisible (mais pas le reste)'), ('3', 'Totalement Invisible')], default='', max_length=30, verbose_name="Visibilité de l'adresse du jardin sur la carte"),
        ),
        migrations.AddField(
            model_name='jardin',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits (visible seulement aux inscrits)'), ('2', 'Invisible')], default='', max_length=30, verbose_name="Visibilité du jardin sur l'annuaire'"),
        ),
        migrations.AddField(
            model_name='jardin',
            name='visibilite_carte',
            field=models.CharField(choices=[('0', 'Adresse, nom et référent visibles publiquement'), ('1', 'Inscrits (visible seulement aux inscrits)'), ('2', 'Adresse invisible (mais pas le reste)'), ('3', 'Totalement Invisible')], default='', max_length=30, verbose_name="Visibilité de l'adresse du jardin sur la carte"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='categorie',
            field=models.CharField(choices=[('0', 'Collectif'), ('1', 'Individuel')], default='', max_length=30, verbose_name='Type de jardin (collectif = associatif, communal, partagé, ouvrier ou familial, etc.)'),
        ),
    ]
