# Generated by Django 2.2.28 on 2023-07-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0030_auto_20230705_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grainotheque',
            name='visibilite_carte',
        ),
        migrations.RemoveField(
            model_name='jardin',
            name='visibilite_carte',
        ),
        migrations.AddField(
            model_name='grainotheque',
            name='visibilite_adresse',
            field=models.CharField(choices=[('0', 'Adresse visible publiquement (carte)'), ('1', 'visible seulement aux inscrits)'), ('2', 'Adresse invisible')], default='', max_length=30, verbose_name="Visibilité de l'adresse de la grainotheque (sur la carte)"),
        ),
        migrations.AddField(
            model_name='jardin',
            name='visibilite_adresse',
            field=models.CharField(choices=[('0', 'Adresse visible publiquement (carte)'), ('1', 'visible seulement aux inscrits)'), ('2', 'Adresse invisible')], default='', max_length=30, verbose_name="Visibilité de l'adresse du jardin (sur la carte)"),
        ),
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits (visible seulement aux inscrits)'), ('2', "Invisible dans l'annuaire")], default='', max_length=30, verbose_name="Visibilité du jardin sur l'annuaire'"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='categorie',
            field=models.CharField(choices=[('0', 'Individuel'), ('1', 'Collectif - associatif'), ('2', 'Collectif - municipal'), ('3', 'Collectif - privé')], default='', max_length=30, verbose_name='Type de jardin (collectif = associatif, communal, partagé, ouvrier ou familial, etc.)'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits (visible seulement aux inscrits)'), ('2', "Invisible dans l'annuaire")], default='', max_length=30, verbose_name="Visibilité du jardin sur l'annuaire'"),
        ),
    ]
