# Generated by Django 2.2.28 on 2023-07-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0031_auto_20230705_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite_adresse',
            field=models.CharField(choices=[('0', 'Adresse visible publiquement (carte)'), ('1', 'Adresse visible seulement aux inscrits)'), ('2', 'Adresse invisible')], default='', max_length=30, verbose_name="Visibilité de l'adresse de la grainotheque (sur la carte)"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='visibilite_adresse',
            field=models.CharField(choices=[('0', 'Adresse visible publiquement (carte)'), ('1', 'Adresse visible seulement aux inscrits)'), ('2', 'Adresse invisible')], default='', max_length=30, verbose_name="Visibilité de l'adresse du jardin (sur la carte)"),
        ),
    ]
