# Generated by Django 2.2.28 on 2023-07-05 22:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0032_auto_20230705_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoGraine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recolte', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de récolte')),
                ('duree_germinative', models.FloatField(verbose_name='Durée de conservation (années)')),
                ('stock_quantite', models.CharField(max_length=120, verbose_name='Quantité de graines (nombre ou grammes)')),
                ('description', models.TextField(help_text='Description (infos supplémentaires, origine, commentaires...)', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='grainotheque',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='jardin',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits (visible seulement aux inscrits)'), ('2', "Invisible dans l'annuaire")], default='', max_length=30, verbose_name="Visibilité de la grainothèque sur l'annuaire"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='categorie',
            field=models.CharField(choices=[('0', 'Individuel'), ('1', 'Collectif - associatif'), ('2', 'Collectif - municipal'), ('3', 'Collectif - privé')], default='', max_length=30, verbose_name='Type de jardin*'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='description',
            field=models.TextField(blank=True, help_text='Décrivez le jardin en quelques mots', null=True),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='email_contact',
            field=models.EmailField(max_length=254, verbose_name='Email de contact*'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='fonctionnement',
            field=models.TextField(blank=True, help_text="Un descriptif du fonctionnement du jardin (horaires, participation, gestion de l'eau, ...)", null=True),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='titre',
            field=models.CharField(max_length=250, verbose_name='Nom du jardin*'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits (visible seulement aux inscrits)'), ('2', "Invisible dans l'annuaire")], default='', max_length=30, verbose_name="Visibilité du jardin sur l'annuaire"),
        ),
        migrations.CreateModel(
            name='Graine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grainotheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardins.Grainotheque')),
                ('infos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jardins.InfoGraine')),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardins.Plante')),
            ],
        ),
    ]
