# Generated by Django 2.2.28 on 2023-07-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0033_auto_20230706_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grainotheque',
            old_name='liste_plantes',
            new_name='description',
        ),
    ]
