# Generated by Django 2.2.28 on 2023-07-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0034_auto_20230706_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='grainotheque',
            name='categorie',
            field=models.CharField(choices=[('0', 'Privée'), ('1', 'Collective - association'), ('2', 'Collective - médiathèque'), ('3', 'Collective - autre')], default='', max_length=3, verbose_name='Type de grainotheque*'),
        ),
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite_adresse',
            field=models.CharField(choices=[('0', 'Adresse visible sans inscription'), ('1', 'Adresse visible seulement aux inscrits)'), ('2', 'Adresse invisible (carte)')], default='', max_length=30, verbose_name="Visibilité de l'adresse de la grainotheque (sur la carte)"),
        ),
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits (visible seulement aux inscrits)'), ('2', "Invisible dans l'annuaire et la carte")], default='', max_length=30, verbose_name="Visibilité de la grainothèque sur l'annuaire"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='categorie',
            field=models.CharField(choices=[('0', 'Individuel'), ('1', 'Collectif - associatif'), ('2', 'Collectif - municipal'), ('3', 'Collectif - privé')], default='', max_length=3, verbose_name='Type de jardin*'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='visibilite_adresse',
            field=models.CharField(choices=[('0', 'Adresse visible sans inscription'), ('1', 'Adresse visible seulement aux inscrits)'), ('2', 'Adresse invisible (carte)')], default='', max_length=30, verbose_name="Visibilité de l'adresse du jardin (sur la carte)"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits (visible seulement aux inscrits)'), ('2', "Invisible dans l'annuaire et la carte")], default='', max_length=3, verbose_name="Visibilité du jardin sur l'annuaire"),
        ),
    ]
