# Generated by Django 2.2.28 on 2023-07-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0035_auto_20230706_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='grainotheque',
            name='email_contact',
            field=models.EmailField(default='test@test.com', max_length=254, verbose_name='Email de contact*'),
        ),
    ]
