# Generated by Django 2.2.28 on 2023-07-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0037_auto_20230706_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infograine',
            name='description',
            field=models.TextField(blank=True, help_text='Description (infos supplémentaires', null=True),
        ),
        migrations.AlterField(
            model_name='infograine',
            name='duree_germinative',
            field=models.FloatField(blank=True, default='5', verbose_name='Durée de conservation (années)'),
        ),
        migrations.AlterField(
            model_name='infograine',
            name='stock_quantite',
            field=models.CharField(blank=True, max_length=120, verbose_name='Quantité de graines (nombre ou grammes)'),
        ),
    ]
