# Generated by Django 2.2.28 on 2023-07-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0039_auto_20230707_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite_adresse',
            field=models.CharField(choices=[('0', 'Adresse visible sans inscription'), ('1', 'Adresse visible seulement par les inscrits'), ('2', 'Adresse invisible (carte)')], default='', max_length=30, verbose_name="Visibilité de l'adresse de la grainotheque (sur la carte)"),
        ),
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits (visible seulement par les inscrits)'), ('2', "Invisible dans l'annuaire et la carte")], default='', max_length=30, verbose_name="Visibilité de la grainothèque sur l'annuaire"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='visibilite_adresse',
            field=models.CharField(choices=[('0', 'Adresse visible sans inscription'), ('1', 'Adresse visible seulement par les inscrits'), ('2', 'Adresse invisible (carte)')], default='', max_length=30, verbose_name="Visibilité de l'adresse du jardin (sur la carte)"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits (visible seulement par les inscrits)'), ('2', "Invisible dans l'annuaire et la carte")], default='', max_length=3, verbose_name="Visibilité du jardin sur l'annuaire"),
        ),
    ]
