# Generated by Django 2.2.28 on 2023-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0040_auto_20230707_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_article', models.CharField(max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
