# Generated by Django 2.2.28 on 2023-07-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0041_genericmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmodel',
            name='type_article',
            field=models.CharField(max_length=100),
        ),
    ]
