# Generated by Django 2.2.28 on 2023-07-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0042_auto_20230707_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', "Public (visible dans l'annuaire sans inscription)"), ('1', 'Inscrits (visible dans seulement par les inscrits au site)'), ('2', "Invisible dans l'annuaire")], default='', max_length=30, verbose_name="Visibilité de la grainothèque sur l'annuaire"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', "Public (visible dans l'annuaire sans inscription)"), ('1', 'Inscrits (visible dans seulement par les inscrits au site)'), ('2', "Invisible dans l'annuaire")], default='', max_length=3, verbose_name="Visibilité du jardin sur l'annuaire"),
        ),
    ]
