# Generated by Django 2.2.28 on 2023-07-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0043_auto_20230708_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grainotheque',
            name='jardin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jardins.Jardin', verbose_name='Jardin associé'),
        ),
    ]
