# Generated by Django 2.2.28 on 2023-07-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0044_auto_20230709_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTG_import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maj_lettre', models.CharField(max_length=2)),
                ('nom', models.CharField(max_length=120)),
                ('famille', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('espece', models.CharField(max_length=50)),
                ('année', models.CharField(max_length=10)),
                ('stock', models.CharField(max_length=10)),
                ('lieu_recolte', models.CharField(max_length=120)),
                ('observations', models.CharField(max_length=120)),
            ],
        ),
    ]
