# Generated by Django 2.2.28 on 2023-07-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0045_rtg_import'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rtg_import',
            old_name='année',
            new_name='annee',
        ),
    ]
