# Generated by Django 2.2.28 on 2023-07-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0046_auto_20230709_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='graine',
            name='nom',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nom de la graine'),
        ),
    ]
