# Generated by Django 2.2.28 on 2023-07-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0047_graine_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graine',
            name='plante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jardins.Plante'),
        ),
    ]
