# Generated by Django 2.2.28 on 2023-07-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0048_auto_20230709_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='PHYLUM',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
