# Generated by Django 2.2.28 on 2023-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0049_auto_20230709_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='CLI',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='EPA',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='FR',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='GF',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='GUA',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='MAR',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='MAY',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='NC',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='NOM_VERN_ENG',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='plante',
            name='PF',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='REU',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='SA',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='SB',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='SM',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='SOUS_FAMILLE',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plante',
            name='SPM',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='TA',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='TAAF',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='TRIBU',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plante',
            name='URL',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plante',
            name='WF',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='plante',
            name='infos_supp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
