# Generated by Django 2.2.28 on 2023-07-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0050_auto_20230709_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtg_import',
            name='stock',
            field=models.CharField(max_length=50),
        ),
    ]
