# Generated by Django 2.2.28 on 2023-07-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0051_auto_20230709_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtg_import',
            name='annee',
            field=models.CharField(max_length=20),
        ),
    ]
