# Generated by Django 2.2.28 on 2023-07-16 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0052_auto_20230709_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grainotheque',
            name='referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referent_grainotheque', to=settings.AUTH_USER_MODEL, verbose_name="Référent (si ce n'est pas vous)"),
        ),
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite_adresse',
            field=models.CharField(choices=[('0', 'Adresse visible sans inscription'), ('1', 'Adresse visible seulement par les inscrits'), ('2', 'Adresse invisible (carte)')], default='', max_length=30, verbose_name="Visibilité de l'adresse de la grainotheque (sur la carte)*"),
        ),
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', "Public (visible dans l'annuaire sans inscription)"), ('1', 'Inscrits (visible dans seulement par les inscrits au site)'), ('2', "Invisible dans l'annuaire")], default='', max_length=30, verbose_name="Visibilité de la grainothèque sur l'annuaire*"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='categorie',
            field=models.CharField(choices=[('0', 'Jardin Collectif - associatif'), ('1', 'Jardin Collectif - municipal'), ('2', 'Jardin Collectif - Privé'), ('3', 'Jardin Individuel - Privé'), ('', 'Jardin Professionnel (maraichage, arboriculture, etc. à usage pro)')], default='', max_length=3, verbose_name='Type de jardin*'),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referent_jardin', to=settings.AUTH_USER_MODEL, verbose_name="Référent (si ce n'est pas vous)"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='visibilite_adresse',
            field=models.CharField(choices=[('0', 'Adresse visible sans inscription'), ('1', 'Adresse visible seulement par les inscrits'), ('2', 'Adresse invisible (carte)')], default='', max_length=30, verbose_name="Visibilité de l'adresse du jardin (sur la carte)*"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', "Public (visible dans l'annuaire sans inscription)"), ('1', 'Inscrits (visible dans seulement par les inscrits au site)'), ('2', "Invisible dans l'annuaire")], default='', max_length=3, verbose_name="Visibilité du jardin sur l'annuaire*"),
        ),
    ]
