# Generated by Django 2.2.28 on 2023-07-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0053_auto_20230716_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grainotheque',
            name='description',
            field=models.TextField(blank=True, help_text='Un descriptif bref de la grianothèque et son fonctionnement', null=True),
        ),
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite_adresse',
            field=models.CharField(choices=[('0', 'Adresse visible sans inscription'), ('1', 'Adresse visible seulement par les inscrits'), ('2', 'Adresse invisible (carte)')], default='', max_length=30, verbose_name="Visibilité de l'adresse de la grainothèque (sur la carte)*"),
        ),
    ]
