# Generated by Django 2.2.28 on 2023-07-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0055_auto_20230716_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grainotheque',
            name='visibilite_adresse',
        ),
        migrations.RemoveField(
            model_name='jardin',
            name='visibilite_adresse',
        ),
    ]
