# Generated by Django 2.2.28 on 2023-07-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0056_auto_20230726_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grainotheque',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits (visible seulement par les inscrits au site)'), ('2', 'Invisible ')], default='0', max_length=30, verbose_name="Visibilité de la grainothèque sur l'annuaire*"),
        ),
        migrations.AlterField(
            model_name='jardin',
            name='visibilite_annuaire',
            field=models.CharField(choices=[('0', 'Public (visible sans inscription)'), ('1', 'Inscrits (visible seulement par les inscrits au site)'), ('2', 'Invisible ')], default='0', max_length=3, verbose_name="Visibilité du jardin sur l'annuaire*"),
        ),
    ]
