# Generated by Django 2.2.28 on 2023-09-09 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0057_auto_20230726_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPlante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Description (infos supplémentaires', null=True)),
                ('type_vegetation', models.CharField(choices=[('0', 'Arbre'), ('1', 'Arbuste'), ('2', 'Plante potagère'), ('3', 'Aromatique / médicinale'), ('4', 'Herbacée'), ('5', 'Liane'), ('6', 'Ornementale')], default='0', max_length=3, verbose_name='Type de plante')),
            ],
        ),
        migrations.AlterField(
            model_name='graine',
            name='infos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardins.InfoGraine'),
        ),
        migrations.CreateModel(
            name='PlanteDeJardin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=120, verbose_name='Nom de la plante')),
                ('infos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jardins.InfoPlante')),
                ('jardin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantedejardin_jardin', to='jardins.Plante')),
                ('plante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantedejardin_plante', to='jardins.Plante')),
            ],
        ),
    ]
