# Generated by Django 2.2.28 on 2023-10-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0061_auto_20230909_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoplante',
            name='type_plante',
            field=models.CharField(choices=[('0', 'Arbre'), ('1', 'Fruitier'), ('2', 'Arbuste'), ('3', 'Plante potagère'), ('4', 'Aromatique / médicinale'), ('5', 'Petit fruit'), ('6', 'Herbacée'), ('8', 'Liane'), ('9', 'Ornementale'), ('10', 'Champignon')], default='0', max_length=3, verbose_name='Type de plante'),
        ),
    ]
