# Generated by Django 2.2.28 on 2024-02-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0062_auto_20231006_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jardin',
            name='categorie',
            field=models.CharField(choices=[('0', 'Jardin Collectif - associatif'), ('1', 'Jardin Collectif - municipal'), ('2', 'Jardin Collectif - Privé'), ('3', 'Jardin Individuel - Privé'), ('4', 'Jardin Professionnel (maraichage, arboriculture, etc. à usage pro)')], default='0', max_length=3, verbose_name='Type de jardin*'),
        ),
    ]
