# Generated by Django 4.2.14 on 2024-07-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0063_auto_20240207_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoplante',
            name='comestibilite',
            field=models.CharField(choices=[('0', 'Inconnu'), ('1', 'non comestible'), ('2', 'Comestible (tout)'), ('3', 'Comestible (feuilles)'), ('4', 'Comestible (fruit)'), ('5', 'Comestible (fleur)'), ('6', 'Comestible (racines)')], default='0', max_length=3, verbose_name='Comestibilité'),
        ),
        migrations.AddField(
            model_name='infoplante',
            name='mellifere',
            field=models.BooleanField(default=False, verbose_name='Plante mellifère'),
        ),
        migrations.AddField(
            model_name='infoplante',
            name='strate',
            field=models.CharField(choices=[('', '----------'), ('0', 'canopée (grand arbre)'), ('1', 'strate arborée basse'), ('2', 'strate arbustive/buissonante'), ('3', 'couche herbacée'), ('4', 'couvre-sol'), ('5', 'rhizosphère'), ('6', 'strate verticale (lianes...)')], default='0', max_length=3, verbose_name='Strate'),
        ),
        migrations.AlterField(
            model_name='infoplante',
            name='type_plante',
            field=models.CharField(choices=[('0', 'Arbre'), ('1', 'Fruitier'), ('2', 'Arbuste'), ('3', 'Plante potagère'), ('4', 'Aromatique / médicinale'), ('5', 'Petit fruit'), ('6', 'Herbacée'), ('8', 'Liane'), ('9', 'Ornementale'), ('10', 'Champignon'), ('11', 'Rhizome')], default='0', max_length=3, verbose_name='Type de plante'),
        ),
    ]
