# Generated by Django 4.2.14 on 2024-07-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0064_infoplante_comestibilite_infoplante_mellifere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantedejardin',
            name='nom',
        ),
        migrations.AlterField(
            model_name='infoplante',
            name='comestibilite',
            field=models.CharField(choices=[('0', 'Comestibilitée inconnue'), ('1', 'non comestible'), ('2', 'Comestible (tout)'), ('3', 'Comestible (feuilles)'), ('4', 'Comestible (fruit)'), ('5', 'Comestible (fleur)'), ('6', 'Comestible (racines)')], default='0', max_length=3, verbose_name='Comestibilité'),
        ),
    ]
