# Generated by Django 4.2.14 on 2024-08-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0067_alter_graine_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infograine',
            name='description',
            field=models.TextField(blank=True, help_text='Description (infos supplémentaires)', null=True),
        ),
        migrations.AlterField(
            model_name='infoplante',
            name='description',
            field=models.TextField(blank=True, help_text='Description (infos supplémentaires)', null=True),
        ),
    ]
