# Generated by Django 2.2.28 on 2023-06-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0033_auto_20220822_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionatelier',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
    ]
