# Generated by Django 2.2.28 on 2024-07-17 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0043_auto_20240717_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atelier',
            name='date_dernierMessage',
        ),
        migrations.RemoveField(
            model_name='atelier',
            name='dernierMessage',
        ),
    ]
