# Generated by Django 2.2.28 on 2023-11-23 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bourseLibre', '0110_auto_20231111_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom du participant')),
                ('prenom', models.CharField(blank=True, max_length=120, verbose_name='Nom du participant')),
                ('statut', models.CharField(max_length=120, verbose_name='Nom du participant')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.Adresse')),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cotisation', models.DateField(verbose_name='Date de la cotisation')),
                ('montant', models.CharField(max_length=50, verbose_name="Montant de l'adhesion")),
                ('moyen', models.CharField(max_length=50, verbose_name='Moyen de paiement')),
                ('detail', models.TextField(blank=True, null=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.Adherent', verbose_name='Adhérent ')),
            ],
        ),
    ]
