# Generated by Django 2.2.28 on 2023-11-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0002_auto_20231123_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='nom',
            field=models.CharField(max_length=120, verbose_name='Nom '),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='prenom',
            field=models.CharField(blank=True, max_length=120, verbose_name='Prénom '),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='statut',
            field=models.CharField(max_length=120, verbose_name='Statut'),
        ),
    ]
