# Generated by Django 2.2.28 on 2023-11-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0003_auto_20231123_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='statut',
            field=models.CharField(max_length=120, verbose_name="Statut d'agriculteur (AP pour 'a titre pincipal', CS pour 'cotisant solidaire')"),
        ),
    ]
