# Generated by Django 2.2.28 on 2023-11-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0004_auto_20231123_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='production_ape',
            field=models.CharField(blank=True, max_length=120, verbose_name='Production (APE) '),
        ),
    ]
