# Generated by Django 2.2.28 on 2023-11-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0007_auto_20231125_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='statut',
            field=models.CharField(choices=[('0', '?'), ('1', 'A titre principal'), ('2', 'Cotisant Solidaire'), ('3', 'CC'), ('4', 'Retraité.e'), ('5', 'ATS')], default='0', max_length=5, verbose_name="Statut d'agriculteur"),
        ),
    ]
