# Generated by Django 2.2.28 on 2023-12-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0008_auto_20231125_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='nom_gaec',
            field=models.CharField(blank=True, max_length=120, verbose_name='Gaec'),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='statut',
            field=models.CharField(choices=[('0', '?'), ('1', 'A titre principal'), ('2', 'Cotisant Solidaire'), ('3', 'Conjoint Collaborateur'), ('4', 'Retraité.e'), ('5', 'ATS'), ('6', 'Porteur de projet')], default='0', max_length=5, verbose_name="Statut d'agriculteur"),
        ),
    ]
