# Generated by Django 2.2.28 on 2023-12-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0009_auto_20231202_1321'),
    ]

    operations = [

        migrations.CreateModel(
            name='ListeDiffusionConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Date de création'),)
            ],
        ),
        migrations.CreateModel(
            name='InscriptionMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('commentaire', models.CharField(blank=True, max_length=50)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.Adherent', verbose_name='Adhérent')),
                ('liste_diffusion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adherents.ListeDiffusionConf', verbose_name='Liste de diffusion')),
            ],
        ),
    ]
