# Generated by Django 2.2.28 on 2024-04-15 08:10
from django.db import migrations

def check_noms(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    adh = apps.get_model('adherents', 'Adherent')
    for art in adh.objects.all():
        qs = adh.objects.filter(nom=art.nom, prenom=art.prenom, )
        if len(qs) > 1:
            art.nom = "_" + art.nom
            art.save()
        art.save()


class Migration(migrations.Migration):
    dependencies = [
        ('adherents', '0010_inscriptionmail_listediffusionconf'),
    ]

    operations = [
        migrations.RunPython(check_noms, ),
        migrations.AlterUniqueTogether(
            name='adherent',
            unique_together={('nom', 'prenom')},
        ),
    ]
