# Generated by Django 2.2.28 on 2023-12-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0010_inscriptionmail_listediffusionconf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeDiffusionConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('date_creation',models.DateTimeField(auto_now=True, verbose_name='Date de création'),)
            ],
        ),
    ]
