# Generated by Django 2.2.28 on 2024-04-15 08:40

from django.db import migrations, models


def check_moyens(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    adh = apps.get_model('adherents', 'Adhesion')
    for a in adh.objects.all():
        if a.moyen == "VIRT" or a.moyen == "virement" or a.moyen == "Virement" or a.moyen == "Vir" or a.moyen == "virt" :
            a.moyen = "VIR"
            a.save()
        elif a.moyen == "Chèque" or a.moyen == "Chq" or a.moyen == "Cheque" or a.moyen == "CHEQUE" or a.moyen == "chq" :
            a.moyen = "CHQ"
            a.save()
        elif a.moyen == "especes" or a.moyen == "Esp" or a.moyen == "Espèce":
            a.moyen = "ESP"
            a.save()

class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0011_auto_20240415_1010'),
    ]

    operations = [
        migrations.RunPython(check_moyens, ),
        migrations.AlterField(
            model_name='adhesion',
            name='moyen',
            field=models.CharField(choices=[('VIR', 'Virement'), ('CHQ', 'Chèque'), ('ESP', 'Espèce'), ('HA', 'HelloAsso'), ('Autre', 'Autre')], max_length=50, verbose_name='Moyen de paiement'),
        ),
    ]
