# Generated by Django 4.2.14 on 2024-11-14 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0013_listediffusionconf_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comm_adherent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('Commentaire', models.CharField(max_length=500, verbose_name='Commentaire')),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.adherent', verbose_name='Adhérent')),
            ],
        ),
    ]
