# Generated by Django 4.2.14 on 2024-11-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0014_comm_adherent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comm_adherent',
            old_name='Commentaire',
            new_name='commentaire',
        ),
    ]
