# Generated by Django 4.2.14 on 2024-11-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0015_rename_commentaire_comm_adherent_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comm_adherent',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
