# Generated by Django 4.2.14 on 2024-11-15 22:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0114_alter_profil_adresse'),
        ('adherents', '0016_alter_comm_adherent_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paysan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=120, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=120, verbose_name='Prénom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=120, verbose_name='Telephone')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.adherent', verbose_name="Adhérent Conf'")),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.adresse')),
            ],
        ),
    ]
