# Generated by Django 4.2.14 on 2024-11-15 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0017_paysan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysan',
            name='adherent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adherents.adherent', verbose_name="Adhérent Conf'"),
        ),
        migrations.AlterField(
            model_name='paysan',
            name='email',
            field=models.CharField(blank=True, max_length=150, verbose_name='Email'),
        ),
    ]
