# Generated by Django 4.2.14 on 2024-11-15 23:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0018_rename_prénom_paysan_prenom_alter_paysan_adherent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPaysan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(blank=True, max_length=200, verbose_name='commentaire')),
                ('date_contact', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('statut', models.CharField(choices=[('0', 'Réponse OK'), ('1', 'Pas de réponse'), ('2', 'à répondu mais à rappeler')], default='0', max_length=2, verbose_name='Statut')),
                ('paysan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.paysan', verbose_name='Paysan')),
            ],
        ),
    ]
