# Generated by Django 4.2.14 on 2024-11-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0019_contactpaysan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paysan',
            name='telephone',
        ),
    ]
