# Generated by Django 4.2.14 on 2024-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0020_remove_paysan_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysan',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='paysan',
            name='nom',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='paysan',
            name='prenom',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Prénom'),
        ),
    ]
