# Generated by Django 4.2.14 on 2024-11-16 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0021_alter_paysan_email_alter_paysan_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysan',
            name='adherent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adherents.adherent', verbose_name="Adhérent Conf'"),
        ),
    ]
