# Generated by Django 4.2.14 on 2024-11-22 23:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone





class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0115_alter_adresse_pays'),
        ('adherents', '0023_alter_contactpaysan_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetPhoning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Nom du projet')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('asso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.asso', verbose_name='Groupe associé')),
            ],
        ),

    ]
