# Generated by Django 4.2.14 on 2024-11-23 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0025_adherent_asso_adhesion_asso_listediffusionconf_asso_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InscriptionMail',
            new_name='InscriptionMail_old',
        ),
    ]
