# Generated by Django 4.2.14 on 2024-11-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0026_rename_inscriptionmail_inscriptionmail_old'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InscriptionMail_new',
            new_name='InscriptionMail',
        ),
    ]
