# Generated by Django 4.2.14 on 2024-11-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0027_rename_inscriptionmail_new_inscriptionmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listediffusionconf',
            name='asso',
        ),
        migrations.DeleteModel(
            name='InscriptionMail_old',
        ),
        migrations.DeleteModel(
            name='ListeDiffusionConf',
        ),
    ]
