# Generated by Django 4.2.14 on 2024-11-25 23:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def copierListesDiffusion(apps, schema_migration):
    Projets = apps.get_model('adherents', 'ProjetPhoning')
    projet_conf = Projets.objects.create(titre="EP CA 2024", asso=asso_conf)

    Contacts = apps.get_model('adherents', 'Contact')

    for a in Contacts.objects.all():
        a.projet = projet_conf
        a.save(update_fields=["projet", ])


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0115_alter_adresse_pays'),
        ('adherents', '0028_remove_listediffusionconf_asso_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPaysan',
            new_name='ContactContact',
        ),
        migrations.RenameModel(
            old_name='Paysan',
            new_name='Contact',
        ),
        migrations.AddField(
            model_name='contactcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.contact', verbose_name='Contact'),
        ),
    ]
