# Generated by Django 4.2.14 on 2024-11-25 23:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0115_alter_adresse_pays'),
        ('adherents', '0028_remove_listediffusionconf_asso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(blank=True, max_length=200, verbose_name='commentaire')),
                ('date_contact', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('statut', models.CharField(choices=[('0', 'Réponse_OK'), ('1', 'Pas de réponse'), ('2', 'A répondu mais à rappeler'), ('3', 'A répondu mais HOSTILE'), ('4', 'Mauvais numéroe')], default='0', max_length=2, verbose_name='Statut')),
            ],
        ),
        migrations.RenameModel(
            old_name='Paysan',
            new_name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactPaysan',
        ),
        migrations.AddField(
            model_name='contactcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.contact', verbose_name='Contact'),
        ),
    ]
