# Generated by Django 4.2.14 on 2024-12-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0029_contactcontact_rename_paysan_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcontact',
            name='paysan',
        ),
    ]
