# Generated by Django 4.2.14 on 2025-01-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0031_contact_commentaire2'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetphoning',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
