# Generated by Django 4.2.14 on 2025-01-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0033_alter_contactcontact_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adherent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adherents.adherent', verbose_name="Adhérent Conf'"),
        ),
        migrations.AlterField(
            model_name='contact',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adherents.projetphoning', verbose_name='Projet associé'),
        ),
    ]
