# Generated by Django 4.2.14 on 2025-01-15 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adherents', '0034_alter_contact_adherent_alter_contact_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcontact',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Profil pcat'),
        ),
        migrations.AlterField(
            model_name='contactcontact',
            name='statut',
            field=models.CharField(choices=[('', '--------'), ('0', 'Réponse OK'), ('1', 'Pas de réponse'), ('2', 'A répondu mais à rappeler'), ('3', 'A répondu mais HOSTILE'), ('4', 'Mauvais numéro'), ('5', "Je l'appellerai")], default='', max_length=2, verbose_name='Statut'),
        ),
    ]
