# Generated by Django 4.2.14 on 2025-05-04 12:48

from django.db import migrations


def ajouterAssoAdhesions(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    adh_1 = apps.get_model('adherents', 'Adherent')
    adh_2 = apps.get_model('adherents', 'Adhesion')
    Assos = apps.get_model('bourseLibre', 'Asso')
    asso_conf = Assos.objects.get(abreviation="public")
    for adh in adh_1.objects.filter(asso__isnull=True):
        adh.asso = asso_conf
        adh.save()
    for adh in adh_2.objects.filter(asso__isnull=True):
        adh.asso = asso_conf
        adh.save()

class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0037_alter_contactcontact_profil'),
    ]

    operations = [

        migrations.RunPython(ajouterAssoAdhesions, ),
    ]
