# Generated by Django 4.2.14 on 2025-05-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0119_alter_favoris_url'),
        ('adherents', '0038_auto_20250504_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionmail',
            name='liste_diffusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.listediffusion', verbose_name='Liste de diffusion'),
        ),
        migrations.AlterUniqueTogether(
            name='adherent',
            unique_together={('nom', 'prenom', 'asso')},
        ),
    ]
