# Generated by Django 4.2.14 on 2025-05-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0039_alter_inscriptionmail_liste_diffusion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscriptionmail',
            unique_together={('liste_diffusion', 'adherent')},
        ),
    ]
