# Generated by Django 4.2.14 on 2025-05-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0040_alter_inscriptionmail_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetphoning',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Nom du projet'),
        ),
    ]
