# Generated by Django 4.2.14 on 2025-05-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0122_profil_css_dark_alter_produit_service_souscategorie'),
        ('adherents', '0041_alter_projetphoning_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.adresse'),
        ),
    ]
