# Generated by Django 4.2.14 on 2025-06-19 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0042_alter_contact_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionmail',
            name='email_pasadherent',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='inscriptionmail',
            name='adherent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adherents.adherent', verbose_name='Adhérent'),
        ),
    ]
