# Generated by Django 4.2.14 on 2025-07-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0045_alter_adherent_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='statut',
            field=models.CharField(choices=[('0', '?'), ('1', 'A titre principal'), ('2', 'Cotisant Solidaire'), ('3', 'Conjoint Collaborateur'), ('4', 'Retraité.e'), ('5', 'ATS'), ('6', 'Porteur de projet'), ('7', 'Aide familial')], default='0', max_length=5, verbose_name="Statut d'agriculteur"),
        ),
    ]
