# Generated by Django 4.2.14 on 2025-09-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0047_alter_adherent_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetphoning',
            name='estArchive',
            field=models.BooleanField(default=False, verbose_name='Archiver le projet (seuls les memrbes du bureau peuvent voir les projets archivés)'),
        ),
    ]
