# Generated by Django 4.2.14 on 2025-09-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0048_projetphoning_estarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetphoning',
            name='estArchive',
            field=models.BooleanField(default=False, verbose_name="Archiver le projet (Il n'apparaitra plus dans la liste)"),
        ),
    ]
