# Generated by Django 4.2.14 on 2025-10-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0137_asso_is_listecontacts_asso_is_listediffusion'),
        ('adherents', '0049_alter_projetphoning_estarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.adresse'),
        ),
    ]
