# Generated by Django 4.2.27 on 2026-07-15 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0140_alter_profil_accepter_annuaire_and_more'),
        ('adherents', '0050_alter_adherent_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listediffusion',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.asso', verbose_name='Groupe associé'),
        ),
    ]
