# Generated by Django 4.2.27 on 2026-10-05 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0051_alter_listediffusion_asso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcontact',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='commentaire'),
        ),
        migrations.AlterField(
            model_name='contactcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='adherents.contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='contactcontact',
            name='statut',
            field=models.CharField(choices=[('', '--------'), ('0', 'Réponse OK'), ('1', 'Pas de réponse'), ('2', 'A répondu mais à rappeler'), ('3', "A répondu mais 'hostile'"), ('4', 'Mauvais numéro ou mail'), ('5', 'RDV pris'), ('6', 'Autre')], default='', max_length=2, verbose_name='Statut'),
        ),
    ]
