# Generated by Django 4.2.27 on 2026-10-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0052_alter_contactcontact_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nom_structure',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Structure'),
        ),
        migrations.AddField(
            model_name='contact',
            name='referent',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Référent-e'),
        ),
        migrations.AddField(
            model_name='contact',
            name='type_structure',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Type'),
        ),
    ]
