# Generated by Django 4.2.14 on 2025-08-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message_permagora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom prénom / Raison sociale')),
                ('msg', models.TextField(verbose_name='Message')),
            ],
        ),
    ]
