# Generated by Django 2.2.28 on 2024-07-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='heure_atelier',
            field=models.TimeField(blank=True, default='14:00', help_text='Horaire de départ (hh:mm)', null=True, verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='heure_atelier_fin',
            field=models.TimeField(blank=True, default='17:00', help_text='Horaire de fin (hh:mm)', null=True, verbose_name='Heure de fin '),
        ),
    ]
