# Generated by Django 4.2.14 on 2025-07-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0002_auto_20240717_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='heure_atelier_fin',
            field=models.TimeField(blank=True, default='17:00', help_text='Horaire de fin (hh:mm)', null=True, verbose_name='Heure de fin'),
        ),
    ]
