# Generated by Django 4.2.14 on 2025-07-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0003_alter_atelier_heure_atelier_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='heure_atelier',
            field=models.TimeField(blank=True, default='14:00', help_text='hh:mm', null=True, verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='heure_atelier_fin',
            field=models.TimeField(blank=True, default='17:00', help_text='hh:mm', null=True, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='tarif_par_personne',
            field=models.CharField(blank=True, default='gratuit', max_length=100, verbose_name="Tarif de l'atelier par personne"),
        ),
    ]
