# Generated by Django 4.2.27 on 2026-02-13 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0004_alter_atelier_heure_atelier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier_recherche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atelier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ateliers.atelier')),
            ],
        ),
    ]
