# Generated by Django 4.2.27 on 2026-02-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0005_atelier_recherche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='nbMaxInscriptions',
            field=models.IntegerField(blank=True, help_text="Nombre maximum de personnes qui peuvent s'inscrire", null=True, verbose_name="Nombre maximum d'inscriptions"),
        ),
    ]
