# Generated by Django 4.2.27 on 2026-03-31 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ateliers', '0006_alter_atelier_nbmaxinscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionatelier',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InscriptionEmailAtelier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ateliers.atelier')),
            ],
        ),
    ]
