# Generated by Django 4.2.27 on 2026-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0007_alter_inscriptionatelier_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaireatelier',
            name='commentaire',
            field=models.TextField(verbose_name=''),
        ),
    ]
