# Generated by Django 2.2.13 on 2021-04-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0019_auto_20210406_2051'),
    ]

    operations = [
    ]
