# Generated by Django 2.2.28 on 2024-04-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0037_atelier_nbmaxinscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='nbMaxInscriptions',
            field=models.IntegerField(blank=True, help_text='Nombre maximum de personnes inscrites', null=True, verbose_name="Nombre maximum d'inscriptions"),
        ),
    ]
