# Generated by Django 2.2.28 on 2024-07-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0041_commentaireatelier_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscriptionatelier_new',
            old_name='atelier_new',
            new_name='atelier',
        ),
    ]
