# Generated by Django 2.2.28 on 2024-01-22 22:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0110_auto_20231025_1054'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0006_auto_20221211_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage_binaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('question', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Question (oui/non) soumise au vote ?')),
                ('article', models.ForeignKey(blank=True, help_text='Article associé', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_suffrage_simple', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteSimple_binaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.IntegerField(choices=[('', '-----------'), (0, 'Oui'), (1, 'Non'), (2, 'Ne se prononce pas')], default=2, verbose_name='Choix du vote :')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_vote_simple', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Sondage_binaire')),
            ],
            options={
                'unique_together': {('auteur', 'question')},
            },
        ),
    ]
