# Generated by Django 4.2.14 on 2025-08-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_sondage_binaire_votesimple_binaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suffrage',
            name='end_time',
            field=models.DateField(help_text='jj/mm/année', null=True, verbose_name='Date de fin du vote (inclu)'),
        ),
    ]
