# Generated by Django 4.2.27 on 2026-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_alter_suffrage_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
