# Generated by Django 2.2.28 on 2023-10-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0105_auto_20231016_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPartage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100, null=True, verbose_name='url de la page')),
                ('slug', models.SlugField(max_length=100)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='article lié')),
            ],
        ),
    ]
