# Generated by Django 2.2.28 on 2023-10-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0107_salon_tags'),
        ('blog', '0108_auto_20231023_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationSalonArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='article lié')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.Salon', verbose_name='Salon lié')),
            ],
        ),
    ]
