# Generated by Django 2.2.28 on 2024-05-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0120_auto_20240509_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='adressearticle',
            name='type_marqueur',
            field=models.CharField(choices=[('0', 'Defaut (vert)'), ('1', 'Defaut (bleu)'), ('2', 'Defaut (rouge)'), ('3', 'Defaut (noir)')], default='0', max_length=5, verbose_name='type_marqueur'),
        ),
    ]
