# Generated by Django 2.2.28 on 2024-05-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0121_adressearticle_type_marqueur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressearticle',
            name='type_marqueur',
            field=models.CharField(choices=[('0', 'Vert (défaut)'), ('1', 'Bleu'), ('2', 'Rouge'), ('3', 'Jaune'), ('4', 'Orange'), ('5', 'Violet'), ('6', 'Or'), ('7', 'Noir'), ('8', 'Gris')], default='0', max_length=5, verbose_name='type_marqueur'),
        ),
    ]
