# Generated by Django 2.2.28 on 2024-07-17 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bourseLibre', '0111_auto_20240220_1317'),
        ('blog', '0122_auto_20240516_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('0', 'Permaculture'), ('1', 'Bricolage'), ('2', 'Cuisine'), ('3', 'Bien-être'), ('4', 'Musique'), ('6', 'Politique'), ('8', 'Culture'), ('7', 'Activité Pro'), ('9', 'Informatique'), ('5', 'Autre...')], default='0', max_length=30, verbose_name='categorie')),
                ('statut', models.CharField(choices=[('0', 'proposition'), ('1', "accepté, en cours d'organisation"), ('2', "accepté, s'est déroule correctement"), ('3', 'a été annulé')], default='proposition', max_length=30, verbose_name="Statut de l'atelier")),
                ('titre', models.CharField(max_length=120, verbose_name="Titre de l'atelier")),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('materiel', models.TextField(blank=True, null=True, verbose_name='Matériel/outils nécessaires')),
                ('referent', models.CharField(blank=True, max_length=120, null=True, verbose_name='Référent(e.s)')),
                ('start_time', models.DateField(blank=True, default=django.utils.timezone.now, help_text='(jj/mm/an)', null=True, verbose_name="Date prévue (affichage dans l'agenda)")),
                ('heure_atelier', models.TimeField(blank=True, default='14:00', help_text='Horaire de départ (hh:mm)', null=True, verbose_name='Heure de début')),
                ('heure_atelier_fin', models.TimeField(blank=True, default='17:00', help_text='Horaire de fin (hh:mm)', null=True, verbose_name='Heure de fin ')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification')),
                ('tarif_par_personne', models.CharField(default='gratuit', help_text="Tarif de l'atelier par personne", max_length=100, verbose_name="Tarif de l'atelier par personne")),
                ('estArchive', models.BooleanField(default=False, verbose_name="Archiver l'atelier")),
                ('nbMaxInscriptions', models.IntegerField(blank=True, help_text='Nombre maximum de personnes inscrites', null=True, verbose_name="Nombre maximum d'inscriptions")),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
                ('asso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.Asso')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='InscriptionAtelier_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Atelier_new')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireAtelier_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Atelier_new')),
                ('auteur_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
