# Generated by Django 4.2.14 on 2024-08-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0123_atelier_new_commentaireatelier_new_inscriptionatelier_new'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='commentaireatelier_new',
        #     name='atelier',
        # ),
        # migrations.RemoveField(
        #     model_name='commentaireatelier_new',
        #     name='auteur_comm',
        # ),
        # migrations.RemoveField(
        #     model_name='inscriptionatelier_new',
        #     name='atelier',
        # ),
        # migrations.RemoveField(
        #     model_name='inscriptionatelier_new',
        #     name='user',
        # ),
        # migrations.DeleteModel(
        #     name='Atelier_new',
        # ),
        # migrations.DeleteModel(
        #     name='CommentaireAtelier_new',
        # ),
        # migrations.DeleteModel(
        #     name='InscriptionAtelier_new',
        # ),
    ]
