# Generated by Django 4.2.14 on 2025-04-11 09:38

from django.db import migrations, models
import django.db.models.deletion

def creer_zones_geo(apps, schema_editor):
    zones = apps.get_model('blog', 'ZoneGeo')
    noms = ["La plaine du Roussillon", "Perpignan", "Albères et Côte Vermeille Illibéris", "Conflent-Canigo", "Vallespir", "Agly Fenouillèdes",  "Ribéral", "Aspres", "Salanque", "Capcir", "Cerdagne",  "Département", "Région", "Catalogne", "Occitanie", "France", "Europe", "Monde", "Univers", "Cosmos..."]
    for n in noms:
        zone, created = zones.objects.get_or_create(titre=n)

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0127_articleliens_articlelienprojet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneGeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='zonegeo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.zonegeo', verbose_name='Zone géographique'),
        ),
        migrations.RunPython(creer_zones_geo, ),
    ]
