# Generated by Django 4.2.14 on 2025-04-11 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0128_zonegeo_article_recherche_article_zonegeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet_recherche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.projet')),
            ],
        ),
    ]
