# Generated by Django 4.2.14 on 2025-04-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0129_projet_recherche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelienprojet',
            name='type_lien',
            field=models.CharField(choices=[('0', 'info sur le projet'), ('1', 'info en lien avec le projet'), ('2', 'budget ou organisation'), ('3', 'Autre')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='articleliens',
            name='type_lien',
            field=models.CharField(choices=[('0', 'thème commun'), ('1', 'info complémentaire'), ('2', 'info mère'), ('3', 'info fille'), ('3', 'info soeur')], default='0', max_length=2),
        ),
    ]
