# Generated by Django 4.2.14 on 2025-04-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0130_alter_articlelienprojet_type_lien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_recherche',
            name='article',
            field=models.ForeignKey(help_text="<p style='color:teal'>Taper 3 lettres du titre de l'article recherché'</p>", on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
        migrations.AlterField(
            model_name='articlelienprojet',
            name='type_lien',
            field=models.CharField(choices=[('0', 'Info sur le projet'), ('1', 'Info en lien avec le projet'), ('2', 'Budget'), ('3', 'Organisation'), ('4', 'Logistique'), ('5', 'Partenaires'), ('6', 'Atelier/rencontre'), ('6', 'Autre')], default='0', max_length=2, verbose_name='Type de lien'),
        ),
        migrations.AlterField(
            model_name='articleliens',
            name='type_lien',
            field=models.CharField(choices=[('0', 'thème commun'), ('1', 'info complémentaire'), ('2', 'info mère'), ('3', 'info fille'), ('3', 'info soeur')], default='0', max_length=2, verbose_name='Type de lien'),
        ),
        migrations.AlterField(
            model_name='projet_recherche',
            name='projet',
            field=models.ForeignKey(help_text="<p style='color:teal'>Taper 3 lettres du titre du projet recherché'</p>", on_delete=django.db.models.deletion.CASCADE, to='blog.projet'),
        ),
    ]
