# Generated by Django 4.2.14 on 2025-04-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0131_alter_article_recherche_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleliens',
            name='type_lien',
            field=models.CharField(choices=[('0', 'Thème commun ou similaire'), ('1', 'Collectif/projet commun ou similaire'), ('2', "L'article englobe/contient (choisir l'article qui est contenu)"), ('3', "L'article est inclu dans l'autre (choisir l'article qui le contient)"), ('4', "info mère (choisir l'article qui hérite)"), ('5', "info fille (choisir l'article qui lègue)"), ('6', 'info soeur')], default='0', max_length=2, verbose_name='Type de lien'),
        ),
    ]
