# Generated by Django 4.2.14 on 2025-04-13 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0132_alter_articleliens_type_lien'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='article_recherche',
        #     name='article',
        #     field=models.ForeignKey(blank=True, help_text="<p style='color:teal'>Taper 3 lettres du titre de l'article recherché'</p>", null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        # ),
    ]
