# Generated by Django 4.2.14 on 2025-05-14 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0136_alter_article_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_recherche',
            name='article',
            field=models.ForeignKey(blank=True, help_text="<p style='color:teal'>Min 2 lettres</p>", null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
        migrations.AlterField(
            model_name='projet_recherche',
            name='projet',
            field=models.ForeignKey(help_text="<p style='color:teal'>Taper 2 lettres du titre du projet recherché'</p>", on_delete=django.db.models.deletion.CASCADE, to='blog.projet'),
        ),
    ]
