# Generated by Django 4.2.14 on 2025-05-16 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0137_alter_article_recherche_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_recherche',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
        migrations.AlterField(
            model_name='projet_recherche',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.projet'),
        ),
    ]
