# Generated by Django 4.2.14 on 2025-06-19 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0140_alter_article_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpartage',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
