# Generated by Django 4.2.14 on 2025-07-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0141_documentpartage_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_time',
            field=models.DateField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de fin (optionnel, pour affichage dans l'agenda"),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_time',
            field=models.DateField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de l'événement (pour apparaitre sur l'agenda, sinon vous pourrez toujours ajouter des évènements depuis l'article) "),
        ),
    ]
