# Generated by Django 4.2.14 on 2025-07-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0142_alter_article_end_time_alter_article_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='estPublic',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='estPublic',
        ),
    ]
