# Generated by Django 4.2.14 on 2025-11-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0146_alter_article_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpartage',
            name='duree',
            field=models.CharField(choices=[('0', 'Semestriel'), ('1', 'Annuel'), ('2', 'Mensuel'), ('3', 'Hebdomadaire')], default='0', max_length=2, verbose_name='Durée du pad'),
        ),
    ]
