# Generated by Django 4.2.27 on 2026-04-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0149_alter_article_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelienprojet',
            name='type_lien',
            field=models.CharField(choices=[('0', 'Info sur le projet'), ('1', 'Info en lien avec le projet'), ('2', 'Budget'), ('3', 'Organisation'), ('4', 'Logistique'), ('5', 'Partenaires'), ('6', 'Atelier/rencontre'), ('7', 'Autre')], default='0', max_length=2, verbose_name='Type de lien'),
        ),
    ]
