# Generated by Django 4.2.27 on 2026-06-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0150_alter_articlelienprojet_type_lien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cercle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='cercle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.cercle'),
        ),
    ]
