# Generated by Django 4.2.27 on 2026-06-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0139_auto_20260520_2205'),
        ('blog', '0151_cercle_projet_cercle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cercle',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.asso'),
        ),
    ]
