# Generated by Django 4.2.27 on 2026-06-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0152_cercle_asso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cercle',
            name='slug',
            field=models.SlugField(default='temp', max_length=100),
            preserve_default=False,
        ),
    ]
