# Generated by Django 4.2.27 on 2026-06-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0139_auto_20260520_2205'),
        ('blog', '0153_cercle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='asso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.asso'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='cercle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.cercle'),
        ),
    ]
