# Generated by Django 4.2.27 on 2026-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0154_alter_projet_asso_alter_projet_cercle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cercle',
            old_name='nom',
            new_name='titre',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='commentaireprojet',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name=''),
        ),
    ]
