# Generated by Django 4.2.27 on 2026-07-01 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0140_alter_profil_accepter_annuaire_and_more'),
        ('blog', '0155_rename_nom_cercle_titre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cercle',
            name='asso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.asso'),
            preserve_default=False,
        ),
    ]
