# Generated by Django 4.2.27 on 2026-07-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0156_alter_cercle_asso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='categorie',
            field=models.CharField(choices=[('Part', 'Participation à un évènement'), ('Projlong', 'Projet a long terme'), ('Projcourt', 'Projet a court terme'), ('Projponct', 'Projet ponctuel')], default='Part', max_length=10, verbose_name='categorie'),
        ),
    ]
