# Generated by Django 4.2.27 on 2026-09-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0159_alter_article_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleliens',
            name='type_lien',
            field=models.CharField(choices=[('0', 'Thème commun ou similaire'), ('1', 'Drageon : Collectif/projet commun ou similaire'), ('2', "Charpentière : info mère (choisir l'article 'fils')"), ('3', "Branche : info fille (choisir l'article 'père')")], default='0', max_length=2, verbose_name='Type de lien'),
        ),
    ]
