# Generated by Django 4.2.27 on 2026-10-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0160_alter_articleliens_type_lien'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvenementAcceuil',
            new_name='EvenementAccueil',
        ),
    ]
