# Generated by Django 4.2.27 on 2026-10-02 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0161_rename_evenementacceuil_evenementaccueil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionCommentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', "J'approuve"), ('dislike', 'Je désapprouve'), ('heart', 'Heart')], max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blog.commentaire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('commentaire', 'utilisateur')},
            },
        ),
    ]
