# Generated by Django 4.2.27 on 2026-10-02 21:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0162_reactioncommentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', help_text='Minimum 6 lettres', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Nom du document (ou lien http)')),
                ('slug', models.SlugField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_lies', to='blog.article', verbose_name='article lié')),
            ],
        ),
    ]
