# Generated by Django 4.2.27 on 2026-10-02 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0163_lienarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lienarticle',
            name='nom',
            field=models.CharField(default='', help_text='Minimum 6 lettres', max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Lien (http...)'),
        ),
    ]
