# Generated by Django 4.2.27 on 2026-10-02 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0164_alter_lienarticle_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lienarticle',
            name='nom',
            field=models.CharField(default='', help_text='Minimum 4 lettres', max_length=100, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Nom'),
        ),
    ]
