# Generated by Django 4.2.27 on 2026-10-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0165_alter_lienarticle_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='lienarticle',
            name='url_dest',
            field=models.CharField(default='', help_text='Url du lien', max_length=200, null=True, verbose_name='Lien (http...)'),
        ),
    ]
