# Generated by Django 4.2.27 on 2026-10-05 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0166_lienarticle_url_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lienarticle',
            name='nom',
            field=models.CharField(blank=True, default='', help_text='Minimum 4 lettres', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Nom'),
        ),
    ]
