# Generated by Django 4.2.27 on 2026-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0018_auto_20210406_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentairefiche',
            name='commentaire',
            field=models.TextField(verbose_name=''),
        ),
    ]
