# Generated by Django 2.2.28 on 2023-01-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0086_auto_20230102_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
