# Generated by Django 2.2.28 on 2023-01-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0087_salon_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion_asso',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
