# Generated by Django 2.2.28 on 2023-01-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0088_adhesion_asso_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion_permacat',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
