# Generated by Django 2.2.28 on 2023-02-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0089_adhesion_permacat_detail'),
    ]

    operations = [

        migrations.CreateModel(
            name='Monnaie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('don', 'Don'), ('troc', 'Troc'), ('pret', 'Prêt'), ('G1', 'G1'), ('Soudaqui', 'Soudaqui'), ('SEL', 'SEL'), ('JEU', 'JEU'), ('HE', 'heureEntraide'), ('Autre', 'Négociable')], default='don', max_length=50, verbose_name='Monnaie')),
                ('slug', models.SlugField(max_length=100)),
                ('estQuantifiable', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite_prix',
            field=models.CharField(choices=[('don', 'Don'), ('troc', 'Troc'), ('pret', 'Prêt'), ('G1', 'G1'), ('Soudaqui', 'Soudaqui'), ('SEL', 'SEL'), ('JEU', 'JEU'), ('HE', 'heureEntraide'), ('Autre', 'Négociable')], default='don', max_length=8, verbose_name='monnaie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='monnaies',
            field=models.ManyToManyField(blank=True, related_name='produit_monnaie', to='bourseLibre.Monnaie', verbose_name='Monnaies: '),
        ),
    ]
