# Generated by Django 2.2.28 on 2023-02-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0090_auto_20230224_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit_aliment',
            name='type_prix',
        ),
        migrations.RemoveField(
            model_name='produit_objet',
            name='type_prix',
        ),
        migrations.RemoveField(
            model_name='produit_offresetdemandes',
            name='type_prix',
        ),
        migrations.RemoveField(
            model_name='produit_service',
            name='type_prix',
        ),
        migrations.RemoveField(
            model_name='produit_vegetal',
            name='type_prix',
        ),
    ]
