# Generated by Django 2.2.28 on 2023-02-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0091_auto_20230224_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='unite_prix',
            field=models.CharField(choices=[('don', 'Don'), ('troc', 'Troc'), ('pret', 'Prêt'), ('G1', 'G1'), ('Soudaqui', 'Soudaqui'), ('SEL', 'SEL'), ('JEU', 'JEU'), ('HE', 'heureEntraide'), ('Autre', 'Négociable')], default='don', max_length=8, verbose_name='monnaie'),
        ),
    ]
