# Generated by Django 2.2.28 on 2023-02-24 21:44

from django.db import migrations, models


def ajouterMonnaie(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    from bourseLibre.constantes import Choix
    mon = apps.get_model('bourseLibre', 'Monnaie')
    for monnaie, nom in Choix.monnaies:
        mon.objects.create(nom=nom, slug=monnaie, estQuantifiable=(monnaie not in Choix.monnaies_nonquantifiables))
    nomMonnaies = [x for x, y in Choix.monnaies]
    prod = apps.get_model('bourseLibre', 'Produit')
    for p in prod.objects.all():
        if p.unite_prix and p.unite_prix in nomMonnaies:
            p.monnaies.add(p.unite_prix)
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0092_auto_20230224_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='monnaies',
            field=models.ManyToManyField(blank=True, related_name='produit_monnaie', to='bourseLibre.Monnaie', verbose_name='Monnaies : '),
        ),
        migrations.RunPython(ajouterMonnaie, ),

    ]
