# Generated by Django 2.2.28 on 2023-02-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0093_auto_20230224_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.CharField(max_length=150, verbose_name='Tarif'),
        ),
    ]
