# Generated by Django 2.2.28 on 2023-02-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0094_auto_20230224_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tarif'),
        ),
    ]
