# Generated by Django 2.2.28 on 2023-02-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0095_auto_20230224_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit_service',
            name='couleur',
            field=models.CharField(choices=[('#ccffcc', '#ccffcc')], default='#ccffcc', max_length=20),
        ),
    ]
