# Generated by Django 2.2.28 on 2023-02-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0096_auto_20230225_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit_aliment',
            name='couleur',
            field=models.CharField(default='#e6f2ff', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit_objet',
            name='couleur',
            field=models.CharField(default='#ffffe6', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit_offresetdemandes',
            name='couleur',
            field=models.CharField(default='#f2c7f1', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit_service',
            name='couleur',
            field=models.CharField(default='#ccffcc', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit_vegetal',
            name='couleur',
            field=models.CharField(default='#e6ffe6', max_length=20),
        ),
    ]
