# Generated by Django 2.2.28 on 2023-06-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0098_auto_20230225_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='commune',
            field=models.CharField(blank=True, default='Perpignan', max_length=50, null=True),
        ),
    ]
