# Generated by Django 2.2.28 on 2023-07-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0099_auto_20230621_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='code_postal',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='commune',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
