# Generated by Django 2.2.28 on 2023-07-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0100_auto_20230706_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionNewsletterGenerique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionNewsletterAsso',
            fields=[
                ('inscriptionnewslettergenerique_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bourseLibre.InscriptionNewsletterGenerique')),
                ('asso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.Asso')),
            ],
            bases=('bourseLibre.inscriptionnewslettergenerique',),
        ),
    ]
