# Generated by Django 2.2.28 on 2023-07-16 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardins', '0054_auto_20230716_1857'),
        ('bourseLibre', '0101_inscriptionnewsletterasso_inscriptionnewslettergenerique'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='jardin',
            field=models.ForeignKey(blank=True, help_text='Le salon peut être associé à un jardin', null=True, on_delete=django.db.models.deletion.CASCADE, to='jardins.Jardin'),
        ),
    ]
