# Generated by Django 2.2.28 on 2023-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0103_auto_20230717_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionnewslettergenerique',
            name='nom_newsletter',
            field=models.CharField(max_length=30),
        ),
    ]
