# Generated by Django 2.2.28 on 2023-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0104_auto_20230717_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='accepter_conditions',
            field=models.BooleanField(default=True, verbose_name="J'ai lu et j'accepte les conditions d'utilisation du site"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='inscrit_newsletter',
            field=models.BooleanField(default=True, verbose_name="J'accepte de recevoir des emails de Perma.cat"),
        ),
    ]
