# Generated by Django 2.2.28 on 2023-10-22 20:16

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('bourseLibre', '0106_profil_adherent_conf66'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Liste de mots-clés séparés par une virgule', related_name='tag_salon', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots clés'),
        ),
    ]
