# Generated by Django 2.2.28 on 2023-11-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0109_evenementsalon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenementsalon',
            name='titre_even',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name="Titre de l'événement (si laissé vide, ce sera le titre du salon de discussion)"),
        ),
    ]
