# Generated by Django 2.2.28 on 2024-02-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0110_auto_20231111_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='telephone',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
