# Generated by Django 4.2.14 on 2024-07-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0111_auto_20240220_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
