# Generated by Django 4.2.14 on 2024-08-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0112_alter_profil_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='newsletter_envoyee',
            field=models.BooleanField(default=False, verbose_name='Newletterenvoyee'),
        ),
    ]
