# Generated by Django 4.2.14 on 2024-11-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0113_profil_newsletter_envoyee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='adresse',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.adresse'),
        ),
    ]
