# Generated by Django 4.2.14 on 2024-11-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0114_alter_profil_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='pays',
            field=models.CharField(blank=True, default='Catalunya', max_length=12, null=True),
        ),
    ]
