# Generated by Django 4.2.14 on 2024-12-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0115_alter_adresse_pays'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
