# Generated by Django 4.2.14 on 2024-12-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0116_messageadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageadmin',
            name='sujet',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
