# Generated by Django 4.2.14 on 2024-12-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0118_favoris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoris',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
