# Generated by Django 4.2.14 on 2025-05-17 12:28

from django.db import migrations, models



def ajouterAssoSSA(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    asso = apps.get_model('bourseLibre', 'Asso')
    asso.objects.create(nom="SSA 66", slug="ssa")


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0120_rename_abreviation_asso_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='newsletter_envoyee',
        ),
        migrations.AddField(
            model_name='profil',
            name='adherent_ssa',
            field=models.BooleanField(default=False, verbose_name='Je suis intéressé.e par la SSA'),
        ),
        migrations.RunPython(ajouterAssoSSA, ),
    ]
