# Generated by Django 4.2.14 on 2025-06-24 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0123_alter_inscritsalon_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='date_messages',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de validation des messages privés'),
        ),
    ]
