# Generated by Django 4.2.14 on 2025-06-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0124_profil_date_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='afficherNbNotifications',
        ),
    ]
