# Generated by Django 4.2.14 on 2025-06-28 16:35

from django.db import migrations, models
import django.db.models.deletion


def ajouterLiensSalons(apps, schema_editor):
    asso  = apps.get_model('bourseLibre', 'Asso')
    salon = apps.get_model('bourseLibre', 'Salon')
    liens = apps.get_model('bourseLibre', 'Lien_AssoSalon')
    if asso.objects.filter(slug="conf66").exists():
        if salon.objects.filter(slug="conf66_bureau_2023").exists():
            s = salon.objects.get(slug="conf66_bureau_2023")
            s.slug = "conf66_bureau"
            s.save()
            asso_conf = asso.objects.get(slug="conf66")
            liens.objects.create(asso=asso_conf, salon=s, slug="bureau")
    if asso.objects.filter(slug="scic").exists():
        if salon.objects.filter(slug="salon-du-cercle-coeur-de-permagora").exists():
            s = salon.objects.get(slug="salon-du-cercle-coeur-de-permagora")
            asso_scic = asso.objects.get(slug="scic")
            liens.objects.create(asso=asso_scic, salon=s, slug="bureau")


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0125_remove_profil_affichernbnotifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lien_AssoSalon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('slug', models.SlugField(max_length=100)),
                ('asso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lien_asso_salon', to='bourseLibre.asso')),
                ('salon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lien_salon_asso', to='bourseLibre.salon')),
            ],
        ),
        migrations.RunPython(ajouterLiensSalons, ),
    ]
