# Generated by Django 4.2.14 on 2025-06-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0126_lien_assosalon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lien_assosalon',
            old_name='slug',
            new_name='slug_type',
        ),
        migrations.AlterUniqueTogether(
            name='lien_assosalon',
            unique_together={('asso', 'slug_type')},
        ),
    ]
