# Generated by Django 4.2.14 on 2025-06-28 17:02

from django.db import migrations, models

def ajouterLiensSalons(apps, schema_editor):
    asso  = apps.get_model('bourseLibre', 'Asso')
    for slugAsso in ["conf66", "scic"]:
        if asso.objects.filter(slug=slugAsso).exists():
            ass = asso.objects.get(slug=slugAsso)
            ass.is_bureau = True
            ass.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0127_rename_slug_lien_assosalon_slug_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asso',
            name='is_bureau',
            field=models.BooleanField(default=False, verbose_name='Le collectif a un bureau dont seuls les membres accéder à certaines infos (=> créer salon avec lien AssoSalon)'),
        ),
        #migrations.RunPython(ajouterLiensSalons, ),
    ]
