# Generated by Django 4.2.14 on 2025-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0128_asso_is_bureau'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('ca', 'Catalan')], default='fr-fr', max_length=10),
        ),
    ]
