# Generated by Django 4.2.14 on 2025-07-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0129_profil_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('ca', 'Catalan')], default='fr', max_length=10),
        ),
    ]
