# Generated by Django 4.2.14 on 2025-07-05 00:45

from django.db import migrations, models


def change_type_salon(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    salons = apps.get_model('bourseLibre', 'Salon')
    for s in salons.objects.all():
        if s.estPublic:
            s.type_salon = 0
        else:
            s.type_salon = 1
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0130_alter_profil_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='type_salon',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Privé (sur invitation)'), (2, "Réservé à tous les membres d'un groupe")], default=0),
        ),
        migrations.RunPython(change_type_salon, ),
    ]
