# Generated by Django 4.2.14 on 2025-07-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0131_salon_type_salon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='estPublic',
        ),
    ]
