# Generated by Django 4.2.14 on 2025-07-05 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0132_remove_salon_estpublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.asso'),
        ),
    ]
