# Generated by Django 4.2.14 on 2025-07-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0133_salon_asso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='type_salon',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Privé (sur invitation)')], default=0),
        ),
    ]
