# Generated by Django 4.2.14 on 2025-07-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0133_salon_asso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='type_salon',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Privé (sur invitation)'), (2, "Réservé à tous les membres d'un groupe du site")], default=0, verbose_name='Type de Salon'),
        ),
    ]
