# Generated by Django 4.2.14 on 2025-07-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0135_remove_produit_estpublique_alter_produit_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asso',
            name='is_adhesions',
            field=models.BooleanField(default=False, verbose_name='Le groupe a un espace adhésions'),
        ),
        migrations.AddField(
            model_name='asso',
            name='is_defraiement',
            field=models.BooleanField(default=False, verbose_name='Le groupe a un espace defraiement'),
        ),
    ]
