# Generated by Django 4.2.14 on 2025-07-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0136_asso_is_adhesions_asso_is_defraiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='asso',
            name='is_listeContacts',
            field=models.BooleanField(default=False, verbose_name='Le groupe a un espace de listes de diffusion'),
        ),
        migrations.AddField(
            model_name='asso',
            name='is_listeDiffusion',
            field=models.BooleanField(default=False, verbose_name='Le groupe a un espace de listes de contacts'),
        ),
    ]
