# Generated by Django 4.2.14 on 2025-11-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0137_asso_is_listecontacts_asso_is_listediffusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='adherent_ducepaj',
            field=models.BooleanField(default=False, verbose_name='Je fais partie du collectif Du Cep au Jus'),
        ),
    ]
