# Generated by Django 4.2.27 on 2026-05-20 20:05

from django.db import migrations

def reset_adherents_rtg(apps, schema_editor):
    profils = apps.get_model('bourseLibre', 'Profil')
    for p in profils.objects.all():
        if p.adherent_rtg:
            p.adherent_rtg = False
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0138_profil_adherent_ducepaj'),
    ]

    operations = [

        migrations.RunPython(reset_adherents_rtg),
    ]
