# Generated by Django 4.2.27 on 2026-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0139_auto_20260520_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='accepter_annuaire',
            field=models.BooleanField(default=True, verbose_name="J'accepte d'apparaître dans l'annuaire du site et la carte et rend mon profil visible par tous"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_bzz2022',
            field=models.BooleanField(default=False, verbose_name="Je fais parti-e du collectif 'Bzzz'"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_citealt',
            field=models.BooleanField(default=False, verbose_name="Je fais parti-e de 'la Cité Altruiste'"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_ducepaj',
            field=models.BooleanField(default=False, verbose_name='Je fais parti-e du collectif Du Cep au Jus'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_fer',
            field=models.BooleanField(default=False, verbose_name='Je suis adhérent-e de Fermille'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_jp',
            field=models.BooleanField(default=False, verbose_name='Je suis intéressé-e par les jardins partagés'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_pc',
            field=models.BooleanField(default=False, verbose_name='Je suis adhérent-e de Permacat'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_rtg',
            field=models.BooleanField(default=False, verbose_name='Je suis adhérent-e de Ramene Ta Graine'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_scic',
            field=models.BooleanField(default=False, verbose_name="Je suis intéressé-e par le collectif 'PermAgora'"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_ssa',
            field=models.BooleanField(default=False, verbose_name='Je  fais parti-e du collectif SSA66'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_viure',
            field=models.BooleanField(default=False, verbose_name="Je fais parti-e du collectif 'Viure'"),
        ),
    ]
