# Generated by Django 4.2.27 on 2026-09-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0140_alter_profil_accepter_annuaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='adherent_permolives',
            field=models.BooleanField(default=False, verbose_name='Je fais parti-e du collectif Récolte Olives'),
        ),
    ]
