# Generated by Django 4.2.27 on 2026-08-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0140_alter_profil_accepter_annuaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='adherent_irri66',
            field=models.BooleanField(default=False, verbose_name='Je fais parti du collectif Irrigants 66'),
        ),
        migrations.AddField(
            model_name='profil',
            name='adherent_jppb',
            field=models.BooleanField(default=False, verbose_name='Je fais parti du collectif du Jardin du Poisson Bêche'),
        ),
    ]
