# Generated by Django 4.2.27 on 2026-09-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0141_profil_adhereni_irri66_profil_adhereni_permolives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='adhereni_irri66',
            new_name='adherent_irri66',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='adhereni_permolives',
            new_name='adherent_permolives',
        ),
    ]
