# Generated by Django 2.2.24 on 2021-11-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0020_auto_20211125_2314'),
        ('jardinpartage', '0020_auto_20211125_0020'),
    ]

    operations = [
    ]
