# Generated by Django 2.2.28 on 2022-11-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0021_merge_20211125_2316'),
        ('jardinpartage', '0021_auto_20221113_2332'),
    ]

    operations = [
    ]
