# Generated by Django 2.2.28 on 2022-11-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0022_merge_20221113_2334'),
        ('jardinpartage', '0022_auto_20221127_2056'),
    ]

    operations = [
    ]
