# Generated by Django 4.2.14 on 2024-08-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0025_auto_20230706_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
