# Generated by Django 2.2.28 on 2023-08-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0028_document_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'get_latest_by': 'date_creation', 'ordering': ['-date_creation'], 'verbose_name': 'album', 'verbose_name_plural': 'albums'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'get_latest_by': 'date_creation', 'ordering': ['-date_creation'], 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='date_added',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='date_added',
            new_name='date_creation',
        ),
    ]
