# Generated by Django 2.2.28 on 2023-10-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0029_auto_20230824_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
