# Generated by Django 4.2.14 on 2025-05-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0031_alter_photo_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_recherche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(blank=True, help_text="<p style='color:teal'>Min 3 lettres</p>", null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.document')),
            ],
        ),
    ]
