# Generated by Django 4.2.14 on 2025-05-14 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0032_document_recherche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_recherche',
            name='document',
            field=models.ForeignKey(blank=True, help_text="<p style='color:teal'>Min 2 lettres</p>", null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.document'),
        ),
    ]
