# Generated by Django 4.2.14 on 2025-05-16 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0033_alter_document_recherche_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_recherche',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.document'),
        ),
    ]
