# Generated by Django 4.2.27 on 2026-07-01 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0034_alter_document_recherche_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_recherche',
            name='document',
            field=models.ForeignKey(blank=True, help_text="<p style='color:teal'>écrire une partie du titre recherché</p>", null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.document'),
        ),
    ]
