# Generated by Django 4.2.27 on 2026-09-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0036_alter_document_recherche_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc',
            field=models.FileField(upload_to='documents/%Y/%m', verbose_name='Document'),
        ),
    ]
