# Generated by Django 4.2.27 on 2026-09-23 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="Expliquer le risque majeur ou l'impact négatif (pas une simple préférence)")),
                ('is_valid_consent_objection', models.BooleanField(default=True, help_text="Est-ce une objection raisonnable d'après le groupe (frein majeur/sécurité) ?")),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('context', models.TextField(help_text='Contexte et problème à résoudre')),
                ('content', models.TextField(help_text='La proposition concrète')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('CLARIFICATION', 'Demande de clarification'), ('OBJECTION_ROUND', "Tour d'objections"), ('OBJECTION_RESPONSE', 'Réponse aux objections'), ('REFORMULATION', 'Reformulation'), ('ACCEPTED', 'Adoptée (Consentement)'), ('REJECTED', 'Refusée')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reformulated_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='gpc.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Piste de résolution ou argumentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('objection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='gpc.objection')),
            ],
        ),
        migrations.AddField(
            model_name='objection',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='gpc.proposal'),
        ),
        migrations.CreateModel(
            name='ClarificationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, help_text="Réponse fournie par l'auteur de la proposition", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='gpc.proposal')),
            ],
        ),
    ]
