# Generated by Django 4.2.27 on 2026-09-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objection',
            name='description',
            field=models.TextField(help_text="Expliquer le risque majeur ou l'impact négatif"),
        ),
        migrations.AlterField(
            model_name='objection',
            name='is_resolved',
            field=models.BooleanField(default=False, help_text="Marqué comme vraie si l'objection a été levée"),
        ),
        migrations.AlterField(
            model_name='objection',
            name='is_valid_consent_objection',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='content',
            field=models.TextField(help_text='La proposition concrète / Formulation actuelle'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('CLARIFICATION', 'Demandes de clarification'), ('OBJECTION_ROUND', 'Recueil des objections'), ('DELIBERATION', 'Délibération & Traitement'), ('ACCEPTED', 'Adoptée (Consentement)'), ('REJECTED', 'Refusée')], default='DRAFT', max_length=30),
        ),
    ]
