# Generated by Django 4.2.27 on 2026-09-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0141_profil_adherent_irri66_profil_adherent_jppb_and_more'),
        ('gpc', '0002_alter_objection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.asso', verbose_name='Groupe'),
        ),
    ]
