# Generated by Django 4.2.27 on 2026-09-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0141_profil_adherent_irri66_profil_adherent_jppb_and_more'),
        ('gpc', '0003_proposal_asso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='asso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.asso', verbose_name='Groupe'),
            preserve_default=False,
        ),
    ]
