# Generated by Django 4.2.27 on 2026-09-28 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gpc', '0004_alter_proposal_asso'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='nbMinVote',
            field=models.IntegerField(blank=True, help_text='Nombre minimum de personnes qui doivent participer pour valider ', null=True, verbose_name='Nombre minimum de participants (pour valider)'),
        ),
        migrations.CreateModel(
            name='ObjectionResolutionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_resolution', models.BooleanField(default=True, help_text="Vrai = Pour lever l'objection, Faux = Contre")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_votes', to='gpc.objection')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('objection', 'voter')},
            },
        ),
    ]
