# Generated by Django 4.2.27 on 2026-09-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpc', '0005_proposal_nbminvote_objectionresolutionvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='nbMinVote',
            field=models.IntegerField(default='1', help_text='Nombre minimum de personnes qui doivent participer pour valider ', verbose_name='Nombre minimum de participants (pour valider)'),
        ),
    ]
