# Generated by Django 4.2.27 on 2026-10-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpc', '0007_phasevote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='content',
            field=models.TextField(help_text='Une ou deux phrases pour prendre une décision claire', verbose_name='La proposition concrète / Formulation actuelle'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='context',
            field=models.TextField(help_text='De quoi parle-t-on ? Liens utiles ?', verbose_name='Contexte et problème à résoudre'),
        ),
    ]
