# Generated by Django 4.2.14 on 2024-11-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=100, verbose_name='Lastname')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('mobile_phone', models.CharField(max_length=100, verbose_name='Mobile phone')),
            ],
        ),
    ]
