# Generated by Django 4.2.27 on 2026-06-15 11:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0152_cercle_asso'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCercle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('cercle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.cercle')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget_previsionnel', models.DecimalField(decimal_places=2, default=0.0, help_text='Budget prévisionnel des dépenses estimées pour ce projet', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('actif', models.BooleanField(default=True)),
                ('budget_cercle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgetprojets', to='compta.budgetcercle')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projet_budget', to='blog.projet')),
            ],
            options={
                'unique_together': {('budget_cercle', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense'), ('TRANSFERT', 'Transfert sortant (vers un autre projet)')], max_length=10)),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='compta.budgetprojet')),
                ('projet_destination', models.ForeignKey(blank=True, help_text="Sélectionner uniquement s'il s'agit d'un transfert", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_recus', to='compta.budgetprojet')),
            ],
        ),
    ]
