# Generated by Django 4.2.27 on 2026-06-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetprojet',
            name='budget_previsionnel',
        ),
    ]
