# Generated by Django 4.2.27 on 2026-06-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0154_alter_projet_asso_alter_projet_cercle'),
        ('compta', '0002_remove_budgetprojet_budget_previsionnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcercle',
            name='cercle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_cercle', to='blog.cercle'),
        ),
    ]
