# Generated by Django 4.2.27 on 2026-06-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0003_alter_budgetcercle_cercle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetprojet',
            unique_together=set(),
        ),
    ]
