# Generated by Django 4.2.27 on 2026-06-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0004_alter_budgetprojet_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetcercle',
            old_name='nom',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='budgetprojet',
            old_name='nom',
            new_name='titre',
        ),
    ]
