# Generated by Django 4.2.27 on 2026-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0005_rename_nom_budgetcercle_titre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='libelle',
            field=models.CharField(max_length=200, verbose_name='Libellé'),
        ),
    ]
