# Generated by Django 4.2.27 on 2026-07-01 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0157_alter_projet_categorie'),
        ('compta', '0006_alter_transaction_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetprojet',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetprojet',
            name='projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projet_budget', to='blog.projet'),
            preserve_default=False,
        ),
    ]
