# Generated by Django 4.2.27 on 2026-07-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0157_alter_projet_categorie'),
        ('compta', '0007_budgetprojet_slug_alter_budgetprojet_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcercle',
            name='cercle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_cercle', to='blog.cercle'),
        ),
    ]
