# Generated by Django 4.2.27 on 2026-07-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0008_alter_budgetcercle_cercle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='projet',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='projet_destination',
            new_name='budget_destination',
        ),
    ]
