# Generated by Django 4.2.27 on 2026-09-28 11:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0009_rename_projet_transaction_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_client', models.CharField(max_length=20, unique=True, verbose_name='Code Client')),
                ('name', models.CharField(max_length=255, verbose_name='Nom ou Raison sociale')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('siret', models.CharField(blank=True, max_length=14, null=True, verbose_name='SIRET')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('seller_name', models.CharField(max_length=255, verbose_name='Nom / Raison sociale du vendeur')),
                ('seller_project', models.CharField(blank=True, max_length=255, verbose_name='Projet / Marque commerciale')),
                ('seller_siret', models.CharField(max_length=14, verbose_name='SIRET du vendeur')),
                ('seller_iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('seller_bic', models.CharField(max_length=11, verbose_name='BIC')),
                ('document_type', models.CharField(choices=[('QUOTE', 'Devis'), ('INVOICE', 'Facture')], default='INVOICE', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé'), ('PAID', 'Payé'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='compta.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_product', models.CharField(max_length=20, unique=True, verbose_name='Code Produit')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire HT (€)')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='FactureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT appliqué')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compta.facture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compta.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
    ]
