# Generated by Django 4.2.27 on 2026-09-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0141_profil_adherent_irri66_profil_adherent_jppb_and_more'),
        ('compta', '0010_client_facture_product_factureitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom / Raison sociale')),
                ('siret', models.CharField(max_length=14, verbose_name='SIRET')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(max_length=11, verbose_name='BIC')),
                ('is_default', models.BooleanField(default=False, verbose_name='Vendeur par défaut')),
                ('adresse', models.TextField(max_length=255, null=True)),
                ('asso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.asso')),
            ],
            options={
                'verbose_name': 'Vendeur',
                'verbose_name_plural': 'Vendeurs',
            },
        ),
        migrations.RemoveField(
            model_name='facture',
            name='seller_bic',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='seller_iban',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='seller_project',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='seller_siret',
        ),
        migrations.AddField(
            model_name='client',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.asso'),
        ),
        migrations.AddField(
            model_name='facture',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.asso'),
        ),

        migrations.CreateModel(
        name='RecuFiscal',
        fields=[
            ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('nom_donateur', models.CharField(max_length=100)),
            ('prenom_donateur', models.CharField(max_length=100)),
            ('adresse_donateur', models.TextField()),
            ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ('date', models.DateField()),
            ('type_versement', models.CharField(choices=[('DON', 'Don'), ('COTISATION', 'Cotisation')], default='DON', max_length=10)),
            ('numero_recu', models.CharField(max_length=20, unique=True)),
            ('asso_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.assoinfo')),
            ],
        ),
        migrations.AddField(
            model_name='facture',
            name='asso_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='compta.assoinfo', verbose_name='AssoInfo'),
            preserve_default=False,
        ),
    ]
