# Generated by Django 4.2.27 on 2026-09-30 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0141_profil_adherent_irri66_profil_adherent_jppb_and_more'),
        ('compta', '0010_client_facture_product_factureitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom / Raison sociale')),
                ('siret', models.CharField(max_length=14, verbose_name='SIRET')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(max_length=11, verbose_name='BIC')),
                ('is_default', models.BooleanField(default=False, verbose_name='Vendeur par défaut')),
                ('adresse', models.TextField(max_length=255, null=True)),
                ('asso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.asso')),
            ],
            options={
                'verbose_name': 'Vendeur',
                'verbose_name_plural': 'Vendeurs',
            },
        ),
        # migrations.CreateModel(
        #     name='Facture',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
        #         ('created_at', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
        #         ('project', models.CharField(blank=True, max_length=255, verbose_name='Projet / Marque commerciale')),
        #         ('document_type', models.CharField(choices=[('QUOTE', 'Devis'), ('INVOICE', 'Facture')], default='INVOICE', max_length=10)),
        #         ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé'), ('PAID', 'Payé'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=10)),
        #         ('is_archived', models.BooleanField(default=False)),
        #         ('asso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.asso')),
        #         ('asso_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='compta.assoinfo', verbose_name='AssoInfo')),
        #     ],
        #     options={
        #         'verbose_name': 'Facture',
        #         'verbose_name_plural': 'Factures',
        #     },
        # ),
        migrations.AddField(
            model_name='client',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.asso'),
        ),
        migrations.AddField(
            model_name='product',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.asso'),
        ),
        migrations.CreateModel(
            name='RecuFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_donateur', models.CharField(max_length=100)),
                ('prenom_donateur', models.CharField(max_length=100)),
                ('adresse_donateur', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('type_versement', models.CharField(choices=[('DON', 'Don'), ('COTISATION', 'Cotisation')], default='DON', max_length=10)),
                ('numero_recu', models.CharField(max_length=20, unique=True)),
                ('asso_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compta.assoinfo')),
            ],
        ),
        # migrations.CreateModel(
        #     name='FactureItem',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
        #         ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT appliqué')),
        #         ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compta.facture')),
        #         ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compta.product', verbose_name='Produit')),
        #     ],
        #     options={
        #         'verbose_name': 'Ligne de facture',
        #         'verbose_name_plural': 'Lignes de facture',
        #     },
        # ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='compta.client', verbose_name='Client'),
        ),
    ]
