# Generated by Django 4.2.27 on 2026-09-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0010_client_facture_product_factureitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
