# Generated by Django 4.2.27 on 2026-09-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0011_facture_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom / Raison sociale')),
                ('project', models.CharField(blank=True, max_length=255, verbose_name='Projet / Marque commerciale')),
                ('siret', models.CharField(max_length=14, verbose_name='SIRET')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(max_length=11, verbose_name='BIC')),
                ('is_default', models.BooleanField(default=False, verbose_name='Vendeur par défaut')),
            ],
            options={
                'verbose_name': 'Vendeur',
                'verbose_name_plural': 'Vendeurs',
            },
        ),
        migrations.RemoveField(
            model_name='facture',
            name='seller_bic',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='seller_iban',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='seller_project',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='seller_siret',
        ),
        migrations.AddField(
            model_name='facture',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='compta.seller', verbose_name='Vendeur'),
            preserve_default=False,
        ),
    ]
