# Generated by Django 4.2.27 on 2026-09-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0141_profil_adherent_irri66_profil_adherent_jppb_and_more'),
        ('compta', '0011_assoinfo_remove_facture_seller_bic_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='facture',
        #     name='is_archived',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AddField(
            model_name='facture',
            name='project',
            field=models.CharField(blank=True, max_length=255, verbose_name='Projet / Marque commerciale'),
        ),
        migrations.AddField(
            model_name='product',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.asso'),
        ),
        migrations.AddField(
            model_name='recufiscal',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.asso'),
        ),
        migrations.AddField(
            model_name='recufiscal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
