# Generated by Django 4.2.27 on 2026-09-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0141_profil_adherent_irri66_profil_adherent_jppb_and_more'),
        ('compta', '0012_facture_is_archived_facture_project_product_asso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code_client',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code Client'),
        ),
    ]
