# Generated by Django 4.2.27 on 2026-09-30 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0141_profil_adherent_irri66_profil_adherent_jppb_and_more'),
        ('compta', '0012_facture_is_archived_facture_project_product_asso'),
    ]

    operations = [
        migrations.AddField(
            model_name='recufiscal',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.asso'),
        ),
        migrations.AddField(
            model_name='recufiscal',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
