# Generated by Django 4.2.27 on 2026-09-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0013_client_asso_facture_asso_product_asso_seller_asso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='project',
        ),
        migrations.AddField(
            model_name='facture',
            name='project',
            field=models.CharField(blank=True, max_length=255, verbose_name='Projet / Marque commerciale'),
        ),
    ]
