# Generated by Django 4.2.27 on 2026-09-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0013_facture_is_archived_facture_project_product_asso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code_product',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code Produit'),
        ),
    ]
