# Generated by Django 4.2.27 on 2026-10-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0014_alter_product_code_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='facture_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé'), ('PAID', 'Payé')], default='DRAFT', max_length=10),
        ),
    ]
