# Generated by Django 4.2.27 on 2026-10-01 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0015_facture_facture_link_alter_facture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'échéance"),
            preserve_default=False,
        ),
    ]
