# Generated by Django 4.2.27 on 2026-10-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0016_facture_date_echeance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assoinfo',
            constraint=models.UniqueConstraint(fields=('asso', 'is_default'), name='unique defaut par Groupe'),
        ),
    ]
