# Generated by Django 4.2.27 on 2026-10-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0017_assoinfo_unique_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='infos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Infos complémentaires'),
        ),
        migrations.AddField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telephone'),
        ),
    ]
