# Generated by Django 4.2.27 on 2026-10-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0018_client_email_client_infos_client_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assoinfo',
            name='siret',
            field=models.CharField(max_length=20, verbose_name='SIRET'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='siret',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SIRET'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='assoinfo',
            name='iban',
            field=models.CharField(max_length=38, verbose_name='IBAN'),
        ),
    ]
