# Generated by Django 4.2.27 on 2026-10-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0019_alter_assoinfo_siret_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='infos',
            field=models.TextField(blank=True, null=True, verbose_name='Infos complémentaires'),
        ),
    ]
