# Generated by Django 4.2.27 on 2026-04-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectifssa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionCLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom prénom / Raison sociale')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='Message (facultatif)')),
            ],
        ),
    ]
