# Generated by Django 4.2.27 on 2026-05-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectifssa', '0002_inscriptioncla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covoit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom prénom')),
                ('villeDepart', models.CharField(max_length=100, verbose_name='Ville de départ')),
                ('telephone', models.CharField(max_length=25, verbose_name='Téléphone')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='Message (facultatif)')),
                ('besoin', models.CharField(choices=[('0', 'Je cherche une place dans une voiture'), ('1', "J'ai 1 place dans ma voiture"), ('2', "J'ai 2 places dans ma voiture"), ('3', "J'ai 3 places dans ma voiture"), ('4', "J'ai 4 (ou plus) places dans ma voiture")], max_length=1, verbose_name="Je propose / j'ai besoin de...")),
            ],
        ),
    ]
