# Generated by Django 4.2.27 on 2026-05-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectifssa', '0004_covoit_date_inscriptioncla_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_collectifssa',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire (interne)'),
        ),
    ]
