# Generated by Django 4.2.27 on 2026-05-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectifssa', '0005_message_collectifssa_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptioncla',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire (interne)'),
        ),
    ]
